js/.changeset/old-apples-attack.md, js/packages/openinference-instrumentation-openai/jest.config.js, js/packages/openinference-instrumentation-openai/src/instrumentation.ts, js/packages/openinference-instrumentation-openai/test/openai.test.ts, js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
resolves #25 
Adds openAI embeddings instrumentaiton
=> feat(js): OpenAI embeddings Instrumentation

js/.changeset/slimy-pears-boil.md, js/packages/openinference-instrumentation-openai/src/instrumentation.ts, js/packages/openinference-instrumentation-openai/test/openai.test.ts
resolves #39 
Adds the ability to get LLM spans from streaming responses. Does this by splitting the stream via `.tee()` and iterating over the chunks.
=> feat(js): opanai chat completion streaming support

python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py
Also, EMBEDDING_EMBEDDINGS is duplicated, so it's removed.
=> fix: embedding model name should be span attribute

README.md
=> chore: fix URL typo in README

js/.changeset/purple-cherries-judge.md, js/.changeset/swift-grapes-joke.md, js/.eslintrc.js, js/packages/openinference-instrumentation-openai/src/instrumentation.ts, js/packages/openinference-instrumentation-openai/test/openai.test.ts, js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
- implements js support for chat completions
- adds corresponding unit test
- adds js `llm.prompts` semantic convention
- updates eslint rules to enforce strict equality
=> feat(js): openai completions

python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_callback.py
Because it's not predictable when the event callbacks are made, relying on automatic context setting can result in incorrect parent-child relationship. This PR enforces the same parent-child relationship provided by Llama-Index by explicitly specifying the parent context at span creation.
Sibling spans under `agent_step` become child spans of the first span (`llm`)
Correct siblings under `agent_step`
=> fix: enforce explicit parent context at span creation for llama-index

js/.changeset/cuddly-shoes-beg.md, js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts, python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py, spec/semantic_conventions.md
frameworks like langchain and other observability platforms have top-level metadata that can be added to spans. This gets us to parity with these frameworks and observability platforms
=> feat(semcov): add metadata

cspell.json, js/.changeset/cuddly-shoes-beg.md, js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts, python/README.md, python/instrumentation/openinference-instrumentation-langchain/examples/chain_metadata.py, python/instrumentation/openinference-instrumentation-langchain/examples/requirements.txt, python/instrumentation/openinference-instrumentation-langchain/pyproject.toml, python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py, python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/lc_span_attributes.py, python/instrumentation/openinference-instrumentation-langchain/tests/openinference/instrumentation/langchain/test_instrumentor.py, python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py, spec/semantic_conventions.md
Adds the ability to serialize langchain specific metadata into the traces via a `langchain` vendor prefix.
=> feat(langchain): add support for chain metadata in spans

python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
=> fix: retain empty strings for template variables

python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request_attributes_extractor.py, python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_response_attributes_extractor.py, python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_utils.py
convert version lookup to a (lazy) function with a cached result
=> fix: avoid openai dependency at import time

python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request.py, python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_stream.py, python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_utils.py, python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_with_span.py, python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/test_instrumentor.py
resolves #233 
Added a description string alongside the span status code when an exception occurs.
The description is formatted in the same way as the OTEL SDK as seen [here](https://github.com/open-telemetry/opentelemetry-python/blob/2b9dcfc5d853d1c10176937a6bcaade54cda1a31/opentelemetry-api/src/opentelemetry/trace/__init__.py#L588), i.e. 
```python
f"{type(exception).__name__}: {exception}"
```
=> feat: add status description for openai instrumentor

python/instrumentation/openinference-instrumentation-bedrock/pyproject.toml, python/instrumentation/openinference-instrumentation-dspy/pyproject.toml, python/instrumentation/openinference-instrumentation-langchain/pyproject.toml, python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml, python/instrumentation/openinference-instrumentation-openai/pyproject.toml, python/openinference-semantic-conventions/pyproject.toml
Moves all openinference python instrumentation out of beta
=> chore: move projects to stable

python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py, python/tox.ini
Ensures that LangChain metadata is always successfully encoded without error.
Resolves https://github.com/Arize-ai/phoenix/issues/2376
=> fix: ensure langchain metadata is always json serializable

python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/__init__.py, python/instrumentation/openinference-instrumentation-bedrock/tests/test_instrumentor.py
Resolves #258 
- Adds token count information if available
- Correctly sets an OpenInference span kind to Bedrock spans
- Associate span information with `input` and `output` for improved rendering
=> fix: Add token counts to bedrock instrumentation

.github/workflows/python-CI.yaml, python/instrumentation/openinference-instrumentation-bedrock/pyproject.toml, python/instrumentation/openinference-instrumentation-dspy/pyproject.toml, python/instrumentation/openinference-instrumentation-langchain/pyproject.toml, python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml, python/instrumentation/openinference-instrumentation-openai/pyproject.toml, python/tox.ini
Add support for Python 3.12
Updates minimum supported version for LlamaIndex from `0.10.1` to `0.10.5`, which appears to be the first version of LlamaIndex with Python 3.12 support.
resolves #272
=> feat: add support for python 3.12

python/instrumentation/openinference-instrumentation-dspy/.gitignore, python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py, python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
Enables users to instrument their DSPy applications before compiling their modules.
=> fix: dspy instrumentation does not break teleprompter compilation

python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
to turn on the printer
```python
from openinference.instrumentation.langchain import _tracer
_tracer._AUDIT_TIMING = True
```
sample print-out
```
_as_input: 0.066ms
_as_output: 0.063ms
_prompts: 0.026ms
_input_messages: 0.007ms
_parse_message_data: 0.022ms
_flatten: 0.024ms
_output_messages: 0.086ms
_prompt_template: 0.019ms
_invocation_parameters: 0.038ms
_model_name: 0.013ms
_token_counts: 0.006ms
_function_calls: 0.004ms
_tools: 0.003ms
_retrieval_documents: 0.002ms
_metadata: 0.005ms
_flatten: 0.491ms
```
=> fix: add printer for run times

python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
This is necessary because the actual timing is no longer real when the handler is called in a separate thread (which can take place long after the run is done).
=> fix: use start and end times from langchain

python/instrumentation/openinference-instrumentation-mistralai/examples/chat_completions_function_calling.py, python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_chat_wrapper.py, python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_request_attributes_extractor.py, python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_response_attributes_extractor.py, python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_utils.py, python/instrumentation/openinference-instrumentation-mistralai/tests/openinference/instrumentation/mistralai/test_instrumentor.py, python/instrumentation/openinference-instrumentation-openai/examples/chat_completions_with_function_calling.py, python/tox.ini
- Adds tool calling support for `mistralai`
- adds tool calling examples for both openai and mistralai
- fixes a mistake with formatting for llm input messages
- bumps up minimum python version to python 3.9
resolves #312
=> feat: add tool calling support for sync and async chat completions for mistralai instrumentation

python/instrumentation/openinference-instrumentation-mistralai/pyproject.toml
The minimum supported version for `mistralai` is Python 3.9. I updated this value in `tox.ini` previously, but forgot to update for `pyproject.toml`.
=> fix: update mistralai minimum python version

cspell.json, js/packages/openinference-instrumentation-openai/package.json, js/packages/openinference-instrumentation-openai/src/instrumentation.ts, js/packages/openinference-instrumentation-openai/test/openai.test.ts, js/pnpm-lock.yaml
resolves #356 
Supports tracing being suppressed by deleting the span from the context. In reality this can possibly be done a bit more elegance but this has the desired effect.
=> feat(js): support trace supression for openai

js/packages/openinference-instrumentation-langchain/src/tracer.ts, js/packages/openinference-instrumentation-langchain/src/types.ts, js/packages/openinference-instrumentation-langchain/src/utils.ts, js/packages/openinference-instrumentation-langchain/test/fixtures.ts, js/packages/openinference-instrumentation-langchain/test/langchain.test.ts, js/packages/openinference-instrumentation-langchain/test/utils.test.ts
Adds support for retrieval documents on retriever spans and invocation parameters / models on llm spans
=> feat(langchainjs): add retrieval and invocation parameters support to tracer

js/.changeset/polite-candles-wash.md, js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
Adds semantic conventions for:
- LLM prompt templates
- LLM prompt template variables
- retrieval documents (root list)
- LLM function calls
- tool name 
- tool description
=> feat: add semantic conventions for prompt template, retrieval documents, tools, and functions

js/.changeset/tiny-coins-knock.md, js/packages/openinference-instrumentation-langchain/examples/instrumentation.ts, js/packages/openinference-instrumentation-langchain/src/instrumentation.ts
Adds a manuallyInstrument method to the LangChainInstrumentation class to allow users to manually instrument Langchain. This is necessary because the `InstrumentationNodeModuleDefinition` will not work with packages that don't have a main in package.json and an index.js see here https://github.com/elastic/require-in-the-middle/blob/main/index.js#L259.
=> feat(langchainjs): add manual instrumentation method to langchain instrumentation

README.md
adds LangChain.js auto instrumentaton package details and example to OpenInference README
=> docs: update readme to include LangChain.js instrumentation

python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_callback.py
Document scores are sometimes numpy values, which will be discarded by protobuf exporter.
=> fix: convert numpy values for protobuf

README.md, js/examples/langchain-express/backend/README.md, js/examples/langchain-express/backend/src/constants.ts, js/examples/langchain-express/backend/src/vector_store/store.ts, js/packages/openinference-instrumentation-langchain/examples/README.md
Resolves #391 
Resolves #392 
- adds readme for example within package
- updates rag in langchain-express example to pull from multiple pages
- adds node recommendations in docs (some commands only work on node 20)
Better RAG
=> docs: update LangChain.js instrumentation docs and improve rag in example

python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py, spec/semantic_conventions.md
Closes https://github.com/Arize-ai/phoenix/issues/2678
- **Add semantic conventions for session and user id**
- **Sort semconv markdown alphabetically**
- **Add user and session id to markdown file**
=> feat: Add `user.id` and `session.id` to semantic conventions

python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/__init__.py
Resolves #447
Adds support for meta vendor in `openinference-instrumentation-bedrock`, based on [Bedrock Documentation](https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-meta.html) for Meta models.
=> feat: add support for meta vendor in openinference-instrumentation-bedrock

python/openinference-instrumentation/src/openinference/instrumentation/__init__.py
=> fix: ensure bazel can discover instrumentation modules in openinference.instrumentations

python/instrumentation/openinference-instrumentation-langchain/tests/openinference/instrumentation/langchain/test_instrumentor.py
The issue is that our type ignores are required on the old version of LangChain, but not required on the new version of LangChain. If we include the type ignore, the new version of LangChain complains about an usused type ignore. Found the solution [here](https://github.com/python/mypy/issues/8823#issuecomment-1556288015).
=> ci: ensure type ignores in langchain tests run across all versions of langchain

python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml, python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/package.py, python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_callback.py, python/tox.ini
LlamaIndex introduced a regression causing streaming LLM responses that result in a 400 to not register their exception and status code information. We are going to ignore this issue as we are about to migrate our LlamaIndex instrumentation away from the existing callback system to the new system.
This test case removes a few lines causing the tests to fail. It also ensures we are pinning `llama-index-core` for our testing.
=> ci: fix llama-index test cases

js/.changeset/green-cheetahs-vanish.md, js/packages/openinference-instrumentation-openai/src/instrumentation.ts, js/packages/openinference-instrumentation-openai/test/openai.test.ts
In some runtimes the module exported is made immutable by the bundler (webpack) or the runtime (deno). This adds a fallback to a closure variable. The old flag is preserved just so that we can still check if a module is patched directly
=> fix(js): fallback patching flag for openAI for immutable modules

cspell.json, js/package.json, js/packages/openinference-instrumentation-langchain/jest.config.js, js/packages/openinference-instrumentation-langchain/package.json, js/packages/openinference-instrumentation-llama-index/examples/instrumentation.ts, js/packages/openinference-instrumentation-llama-index/examples/llamaindex-node.ts, js/packages/openinference-instrumentation-llama-index/jest.config.js, js/packages/openinference-instrumentation-llama-index/package.json, js/packages/openinference-instrumentation-llama-index/src/index.ts, js/packages/openinference-instrumentation-llama-index/src/instrumentation.ts, js/packages/openinference-instrumentation-llama-index/test/llamaIndex.test.ts, js/packages/openinference-instrumentation-openai/package.json, js/pnpm-lock.yaml
resolves #496 
Initial scaffolding for instrumentation for llamaindex.TS. Adds spans for query.
Note: this uses patching because the Callback manager for llamaindex.ts seems extremely rudimentary and probably will not cover all cases. It also is not documented in any notable way
=> feat(llamaindex.TS): llama-index-ts initial package creation

python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_handler.py
resolves #501 
llama-index-latest is fixed, but mistralai is broken
```
py38-ci-llama_index: OK ✔ in 1 minute 26.78 seconds
py38-ci-llama_index-latest: OK ✔ in 1 minute 30.56 seconds
py312-ci-llama_index: OK ✔ in 1 minute 45.36 seconds
py312-ci-llama_index-latest: OK ✔ in 1 minute 47.66 seconds
```
```
py39-ci-mistralai: FAIL ✖ in 29.79 seconds
py39-ci-mistralai-latest: FAIL ✖ in 29 seconds
py312-ci-mistralai: FAIL ✖ in 33.01 seconds
py312-ci-mistralai-latest: FAIL ✖ in 33.97 seconds
```
=> refactor: fix tests for llama-index latest

python/instrumentation/openinference-instrumentation-langchain/tests/openinference/instrumentation/langchain/test_instrumentor.py, python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
```
>           assert (rqa_span.events[0].attributes or {}).get(
OTELSpanAttributes.EXCEPTION_TYPE
) == "BadRequestError"
E           AssertionError: assert 'openai.BadRequestError' == 'BadRequestError'
E             - BadRequestError
E             + openai.BadRequestError
E             ? +++++++
```
=> chore: fix langchain tests for python 12

python/instrumentation/openinference-instrumentation-langchain/pyproject.toml, python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/__init__.py, python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py, python/instrumentation/openinference-instrumentation-langchain/tests/openinference/instrumentation/langchain/test_instrumentor.py
part of https://github.com/Arize-ai/phoenix/issues/3775
1. `langchain-core>=0.1.5` is needed because `var_child_runnable_config` was added by this [commit](https://github.com/langchain-ai/langchain/commit/4e4b11961432203f4b53a63cc428ea631d7cc970#diff-a7db1a221ffd895fa02a23efd3dcecbad235fe1abe1f2859246bf2dbd1430aa6R99) on Dec 29, 2023.
2. Note that OTEL has a similar [facility](https://opentelemetry.io/docs/languages/python/instrumentation/#get-the-current-span) (see below), but we can't use that for LangChain, because we rely on LangChain's own context management for parent-child-span associations.
```python
from opentelemetry import trace
current_span = trace.get_current_span()
```
=> feat: helper function to `get_current_span()` for langchain

python/openinference-instrumentation/src/openinference/instrumentation/guardrails, python/openinference-instrumentation/src/openinference/instrumentation/vertexai
when doing development, it’s not possible to have editable installs for more than one instrumentor at a time because they would just clobber each other due to the shared parent directory
=> chore: add symlinks for editable installs

python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_stream.py, python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/test_instrumentor.py
OpenAI responses can be used as a context manager. For example, see [here](https://github.com/langchain-ai/langchain/blob/dc42279eb55fbb8ec5175d24c7b30fe7b502b6d1/libs/partners/openai/langchain_openai/chat_models/base.py#L513) in LangChain. When that happens, the `__enter__` method on the wrapped stream object is called and the stream object is [returned](https://github.com/openai/openai-python/blob/435a5805ccbd5939a68f7f359ab72e937ef86e59/src/openai/_streaming.py#L103-L104), escaping our wrapper. Subsequent iteration of the stream is un-noticed by our span, and the span is missing because it's never exported. This PR overrides the `__enter__` method so the wrapped object does not escape.
=> fix(openai): missing span when stream response is used as context manager

python/openinference-instrumentation/src/openinference/instrumentation/vertexai
When doing development, it’s not possible to have editable installs for more than one instrumentor at a time because they would just clobber each other due to the shared parent directory. Having symlinks let us editable install just the parent package i.e. `instrumentation`.
=> chore: add symlink for vertexai editable install

js/packages/openinference-core/jest.config.js, js/packages/openinference-core/package.json, js/packages/openinference-core/src/trace/session.ts, js/packages/openinference-core/test/session.test.ts, js/packages/openinference-core/tsconfig.json, js/pnpm-lock.yaml
resolves #655 
Adds session context attributes so that child spans can inherit these attributes
=> feat(openinference-core): js support for sessions

python/openinference-instrumentation/src/openinference/instrumentation/crewai, python/openinference-instrumentation/src/openinference/instrumentation/haystack, python/openinference-instrumentation/src/openinference/instrumentation/litellm
When doing development, it’s not possible to have editable installs for more than one instrumentor at a time because they would just clobber each other due to the shared parent directory. Having symlinks lets us editable install just the parent package i.e. `openinference-instrumentation`.
=> chore: add symlinks to new libs for editable install

js/.changeset/good-avocados-sell.md, js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
- adds missing evaluator span kind, reranker, metadata, tag, and tool parameter semantic conventions to js package, this brings the js package up to date with the python semantic conventions package
=> feat(semantic-conventions): add reranker, metadata, tag, and tool parameters to semantic conventions

js/packages/openinference-core/src/trace/contextAttributes.ts, js/packages/openinference-core/src/trace/index.ts, js/packages/openinference-core/src/trace/types.ts, js/packages/openinference-core/src/utils/index.ts, js/packages/openinference-core/src/utils/typeUtils.ts, js/packages/openinference-core/test/trace/contextAttributes.test.ts
resolves #776 
- adds support for userId, tags, and catch all attributes to be set and read from context
=> feat(openinference-core): add support for userId, attributes, and tags

python/instrumentation/openinference-instrumentation-haystack/examples/requirements.txt, python/instrumentation/openinference-instrumentation-haystack/examples/web_questions.py
Adds an example from the quickstart that uses openAI to ask questions about a website. 
Note this breaks and cases an error tracked in #807
=> docs(haystack): web questions example

js/examples/langchain-express/compose.yml, js/examples/llama-index-express/compose.yml, js/examples/openai/compose.yml
- moves openai example to latest of phoenix now that annotations are in
- forces pull of latest images to avoid staleness
=> docs(examples): move phoenix image version to latest for openai example

python/instrumentation/openinference-instrumentation-haystack/pyproject.toml
This update ensures that important attributes such as span kind are not lost when many attributes are added.
resolves #899
=> fix(haystack): ensure important attributes such as span kind are not lost

python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/_wrappers.py
Improves heuristic for identifying component type on a Haystack component. Previously, there were components such as document splitters and cleaners that were being identified as retrievers.
resolves #899
resolves #885
=> fix(haystack): improve heuristic for identifying component type

js/.changeset/tasty-numbers-try.md, js/packages/openinference-instrumentation-langchain/src/instrumentation.ts
A user was facing runtime issues with the langchain instrumentor trying to modify the package
```
@opentelemetry/api: Registered a global for diag v1.8.0.
URL path should not be set when using grpc, the path part of the URL will be ignored.
Unknown compression "", falling back to "none"
URL path should not be set when using grpc, the path part of the URL will be ignored.
@opentelemetry/api: Registered a global for trace v1.8.0.
@opentelemetry/api: Registered a global for context v1.8.0.
@opentelemetry/api: Registered a global for propagation v1.8.0.
Manually instrumenting @langchain/core/callbacks
Applying patch for @langchain/core/callbacks
[17:49:48.194] WARN (xxx/79773):
msg: "pino.final with prettyPrint does not support flushing"
[17:49:48.195] ERROR (xxx/79773): Uncaught Exception, …
```
=> fix(langchainjs): account for non-mutabable package installs for langchain

python/instrumentation/openinference-instrumentation-guardrails/README.md, python/instrumentation/openinference-instrumentation-guardrails/pyproject.toml, python/instrumentation/openinference-instrumentation-guardrails/src/openinference/instrumentation/guardrails/__init__.py, python/tox.ini
after version 0.5.2 guardrails has major changes that makes the autoinstrumentor here useless. The package after that version also has native instrumentation that works quite well so we'll limit our tox testing to versions < 0.5.2 and for anyone that uses this instrumentor with a version of guardrails >= 0.5.2 the auto instrumentor will be a no op.
=> feat(guardrails): limit support to versions <0.5.2

.github/workflows/typescript-CI.yaml, .github/workflows/typescript-publish.yaml, .gitignore, js/.npmrc, js/DEVELOPMENT.md, js/package.json, js/pnpm-lock.yaml
https://github.com/pnpm/pnpm/releases/tag/v9.7.0
https://github.com/pnpm/pnpm/pull/8363
In order for the packageManger field to be picked up global pnpm must be >=9.7.0.
After that when you're in the js directory any pnpm commands will use the version specified in package json
=> chore: update pnpm version and pin in package.json

js/.changeset/young-horses-grab.md, js/packages/openinference-vercel/src/AISemanticConventions.ts, js/packages/openinference-vercel/src/constants.ts, js/packages/openinference-vercel/src/utils.ts, js/packages/openinference-vercel/test/OpenInferenceSpanProcessor.test.ts
- removes double token counts from `ai.generateText` spans and their children `ai.generateText.doGenerate`, now only the `LLM` span (doGenerate) will have token counts
- adds `input.value` and `output.value` (and respective mime types) to tool spans
see here: https://github.com/Arize-ai/openinference/issues/785#issuecomment-2305233727
and here: https://github.com/Arize-ai/openinference/issues/785#issuecomment-2305278582
for more info
=> fix(vercel): add input / output to tool spans, remove duplicate token counts

js/.changeset/dirty-years-draw.md, js/.changeset/violet-turtles-yawn.md, js/packages/openinference-core/src/utils/index.ts, js/packages/openinference-core/test/trace/utils.test.ts, js/packages/openinference-vercel/src/utils.ts
- adds the ability to have a custom message to log in functions wrapped with `withSafety`, if not passed in does not log anything.
We use `withSafety` in various packages throughout open inference. In some cases we do so expecting the function to succeed, but don't want to throw in someones application when we hit an unexpected error. In this case, it makes sense to log and swallow to return null. In other cases, specifically with safelyJSONParse we use it to merely see if something is parsable - and the error / message is not really worth logging as it is more of a validation check of some unknown things structure (i.e., we expect it to fail some of the time).
It's debatable whether or not we want to use safelyJSONParse in situations where we are checking the structure of something (vs. …
=> feat(core): remove automatic loggin in withSafety function

python/dev-requirements.txt, python/instrumentation/openinference-instrumentation-llama-index/README.md, python/instrumentation/openinference-instrumentation-llama-index/examples/requirements.txt, python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml, python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/__init__.py, python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py, python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_handler_config.py, python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_handler_multimodal.py
=> fix(llama-index): Follow naming convention of private attributes

js/examples/next-openai-telemetry-app/instrumentation.ts, js/examples/next-openai-telemetry-app/package-lock.json, js/examples/next-openai-telemetry-app/package.json
Switch to the new Vercel integration that let's you trim non-openinference spans.
=> docs: update vercel example to use 1.0 span processor

python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_callback.py
A observability platform should not stop business logic from running, so having a `ValueError` raised here is problematic.
```python
> Running step 0d82d966-58b8-442a-b465-1cdc33e2268e. Step input: Can you generate a character for me?
Thought: (Step 1 of 5) I will use the create_character tool to generate a character.
Action: create_character
Action Input: {'first_name': 'John', 'last_name': 'Doe', 'age': 30, 'sex': 'M'}
ERROR [openinference.instrumentation.llama_index._callback] Failed to convert payload to semantic attributes. event_type=CBEventType.FUNCTION_CALL, payload={<EventPayload.FUNCTION_CALL: 'function_call'>: {'first_name': 'John', 'last_name': 'Doe', 'age': 30, 'sex': 'M'}, <EventPayload.TOOL: 'tool'>: ToolMetadata(description='create_character(year: int = …
```
=> fix: Don't check length when converting ToolMetadata to OpenAI format

python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_callback.py
resolves: https://github.com/Arize-ai/openinference/issues/1008
It's hard to pin-point which version of llama-index stopped propagating the errors from child to parent span, but ultimately it doesn't matter because this is the legacy callback.
=> ci(llama-index): remove failing checks in tests because they're not important

python/instrumentation/openinference-instrumentation-litellm/tests/test_instrumentor.py, python/tox.ini
LiteLLM updated their `Usage` and `OpenAIChatCompletion` objects so they are now imported differently so unit tests pass
=> ci: update imports so liteLLM tests pass

.gitignore, python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py, python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
In version 2.5.0, DSPy introduced the notion of an adapter, a layer between the new `LM` interface and `Predict`. This instruments adapters as a chain span kind.
For details, see https://dspy-docs.vercel.app/docs/building-blocks/language_models#structured-lm-output-with-adapters
=> feat(dspy): add instrumentation for dspy adapters

python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py, python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/cassettes/test_instrumentor/test_context_attributes_are_instrumented.yaml, python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
`tracer.start_as_current_span` handles adding exception events and setting the span status automatically. The way we've been doing it adds duplication exception events.
Also improves test case.
=> fix(dspy): prevent the creation of duplicate span exception events

python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/__init__.py, python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py, python/instrumentation/openinference-instrumentation-langchain/tests/test_instrumentor.py
partially resolves #4158
resolves #1052 
Adds a utility to get the most recent chain span that can be found traversing up the trace tree. This will help grab the most appropriate span for sending user feedback.
=> feat: Add `get_chain_root_span` utility for langchain instrumentation

cspell.json, js/.changeset/wild-maps-notice.md, js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts, python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py, spec/semantic_conventions.md
Adds conventions for llm.system and llm.provider so that collectors and user can more easily distinguish different permutations of systems and providers (e.g. `openai` system on `azure` etc)
=> feat(semcov): llm system and llm provicer conventions

js/.changeset/khaki-students-attend.md, js/DEVELOPMENT.md, js/packages/openinference-core/test/trace-config/OITracer.test.ts, js/packages/openinference-instrumentation-langchain/src/instrumentation.ts, js/packages/openinference-instrumentation-langchain/src/instrumentationUtils.ts, js/packages/openinference-instrumentation-langchain/src/tracer.ts, js/packages/openinference-instrumentation-langchain/test/instrumentationUtils.test.ts, js/packages/openinference-instrumentation-langchain/test/langchainV1.test.ts, js/packages/openinference-instrumentation-langchain/test/langchainV2.test.ts, js/packages/openinference-instrumentation-openai/jest.config.js, js/packages/openinference-instrumentation-openai/src/instrumentation.ts, js/packages/openinference-instrumentation-openai/test/openai.test.ts, js/packages/openinference-vercel/README.md
resolves https://github.com/Arize-ai/phoenix/issues/5084
- adds OITracer to openai and langchain instrumentors
- updates developer readme for js to ensure core functionality is added to instrumentations
=> feat: add OITracer to autoinstrumentations providing support for attribute masking and context attribute inheritance

python/instrumentation/openinference-instrumentation-dspy/examples/requirements.txt, python/instrumentation/openinference-instrumentation-dspy/pyproject.toml, python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/package.py, python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
DSPy seems to have two packages, `dspy` and `dspy-ai`. The latter installs the former, and the former now seems to be the recommended way to install the package in the docs. This change should support both. Also makes flaky test less strict.
resolves #1111
=> fix(dspy): instrument `dspy` rather than `dspy-ai`

python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py, python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_handler.py
resolves https://github.com/run-llama/llama_index/issues/16914
=> fix: remove attaching and detaching of opentelemetry contexts

js/.changeset/dirty-candles-brake.md, js/packages/openinference-instrumentation-openai/src/instrumentation.ts
resolves #1061 
- spans created as apart of the work instrumented in the OpenAIInstrumetation will now be properly nested under those spans, for example http instrumentation see:
=> fix(js): set spans from instrumentation active span on context in OpenAI instrumentor

spec/semantic_conventions.md
https://github.com/Arize-ai/openinference/blob/47cd6b5dca3c4e283aefb4d3299425cc2bc80b1c/python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py#L330-L337
=> chore: remove non-existent `llm.provider` value from markdown table

js/.changeset/mean-walls-talk.md, js/packages/openinference-instrumentation-langchain/src/utils.ts, js/packages/openinference-instrumentation-langchain/test/utils.test.ts
=> fix(langchain-js): add token counts for ChatBedrock models

python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/_wrappers.py, python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/cassettes/test_instrumentor/test_anthropic_instrumentation_messages.yaml, python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/test_instrumentor.py
when the model argument is latest, we should record the actual model name from the response
=> fix: capture anthropic model name from response

python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request.py
resolves https://github.com/Arize-ai/phoenix/issues/5303
https://developers.googleblog.com/en/gemini-is-now-accessible-from-the-openai-library/
=> feat: add google as provider for openai instrumentor

js/.changeset/shaggy-goats-love.md, js/packages/openinference-instrumentation-langchain/examples/chat.ts, js/packages/openinference-instrumentation-langchain/src/tracer.ts, js/packages/openinference-instrumentation-langchain/src/utils.ts, js/packages/openinference-instrumentation-langchain/test/langchainV1.test.ts, js/packages/openinference-instrumentation-langchain/test/langchainV2.test.ts, js/packages/openinference-instrumentation-langchain/test/langchainV3.test.ts
Parses metadata with key name in (session_id, thread_id, conversation_id) into semantic conventions session id
=> feat(js): add session id parsing to langchain instrumentation

js/.changeset/mighty-mangos-search.md, js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts, python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py, spec/semantic_conventions.md
This adds audio conventions for placing audio inside of payloads that use things like the realtime api
=> feat(semcov): audio conventions

js/pnpm-lock.yaml
forgot to rerun pnpm install to remove deps from lock file after removing llamaindex in https://github.com/Arize-ai/openinference/pull/1156
=> fix: update lock file after removal of llamaindex package

js/README.md
Typescript does not like the omission of `@opentelemetry/instrumentation` from our list of suggested otel sdk deps.
Installing it manually removes type errors in our sample instrumentation code further down in this document.
=> chore(js): Update quick start dependency list

python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py, python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/conftest.py, python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_multiple_embedding_events.py
=> fix: handle multiple embedding events for llama-index

python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml, python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/__init__.py, python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/conftest.py, python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_get_current_span.py
resolves https://github.com/Arize-ai/phoenix/issues/5379
=> feat: add get_current_span helper function for llama-index

python/examples/README.md
Fix broken `CONTRIBUTING.md` link in the examples subfolder to point to correct file located in root.
=> docs: update `CONTRIBUTING.md` to point to the correct file

python/openinference-instrumentation/pyproject.toml, python/openinference-instrumentation/src/openinference/instrumentation/config.py, python/openinference-instrumentation/tests/test_config.py
=> feat: add ability to hide LLM invocation paramaters for OITracer

python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml, python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py, python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/cassettes/TestToolCallsInChatResponse.test_anthropic.yaml, python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/cassettes/TestToolCallsInChatResponse.test_openai.yaml, python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_callback.py, python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_handler.py, python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_handler_config.py, python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_handler_multimodal.py, python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_tool_calls_response.py, python/tox.ini
=> fix(llama-index): capture tool calls from anthropic chat response

spec/semantic_conventions.md
Adjusting the example for llm.tools to make it consistent with how other list of object semantic conventions are repented in the documentation, so that it doesn't convey that there's something actually different in its structures compared to any other list of objects semantic convention, such as llm.input_messages and llm.output_messages. Ultimately, these open inference semantic conventions are flattened and not nested when ingested via OTLP (e.g. `llm.tools.0.tool.id, `llm.tools.1.tool.id` for semantic conventions that use list of objects), so there is no actual difference in the structure of the data between semantic conventions of the same type. 
Furthermore, some systems may choose to represent conventions like a list of objects  as a single column as opposed to a flattened set of …
=> chore: Adjust llm.tools semantic convention example

python/instrumentation/openinference-instrumentation-smolagents/pyproject.toml, python/instrumentation/openinference-instrumentation-smolagents/src/openinference/instrumentation/smolagents/_wrappers.py
=> fix(smolagents): update internal smolagents import for compatibility with versions post 1.5.0

python/instrumentation/openinference-instrumentation-smolagents/src/openinference/instrumentation/smolagents/_wrappers.py
llm `output.value` is already correctly handled in `_output_value_and_mime_type`.
Fixes #1206
=> fix(smolagents): remove redundant smolagents llm output.value causing warning

python/instrumentation/openinference-instrumentation-smolagents/pyproject.toml, python/instrumentation/openinference-instrumentation-smolagents/src/openinference/instrumentation/smolagents/_wrappers.py, python/instrumentation/openinference-instrumentation-smolagents/tests/openinference/instrumentation/smolagents/test_instrumentor.py
huggingface/smolagents#280 renamed `get_json_schema` to `get_tool_json_schema`.
#1229 got confused with a helper function `get_json_schema` added in  huggingface/smolagents#253.
This causes an issue in `ToolCallingAgent`, although it coincidentally works in `CodeAgent`.
This PR uses the correct function for proper tool schema extraction.
=> fix(smolagents): use correct smolagents tool schema extraction function

js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts, python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py, python/openinference-semantic-conventions/tests/openinference/semconv/test_attributes.py
resolves https://github.com/Arize-ai/phoenix/issues/6152
- Adds `prompt`- based semantic conventions
- These are not nested under the `llm` prefix as they aren't necessarily associated with llm calls
- Consider a case where two prompts are pulled and one is chosen by an agent
=> feat: Add prompt-related semantic conventions

.github/workflows/python-CI.yaml, .github/workflows/typescript-CI.yaml
resolves #1214 
example screenshot of python ci
=> ci: use paths-filter in py and js CI

python/instrumentation/openinference-instrumentation-litellm/src/openinference/instrumentation/litellm/__init__.py
=> fix: use safe_json_dumps for invocation parameters in litellm instrumentor

python/instrumentation/openinference-instrumentation-smolagents/pyproject.toml
I mentioned this to @mikeldking, that openinference can become automatically enabled with [opentelemetry's zero code approach for python](https://opentelemetry.io/docs/zero-code/python/#configuring-the-agent), by adding entrypoints into the pyproject.toml.
Specifically, after this, as long as you have the dependencies of your main code, plus openinference-instrumentation-smolagents, and env exported with standard variables, if you launch with `opentelemetry-instrument`, traces will magically appear.
```bash
opentelemetry-instrument python main.py
```
Before adding to all projects, I wanted to check with smolagents first, if this is ok with y'all. I would love to be able to showcase this with Elastic Distribution of OpenTelemetry (EDOT) and the diff makes it all perfectly invisible. …
=> feat(smolagents): add entrypoint for use in opentelemetry-instrument

python/instrumentation/openinference-instrumentation-anthropic/pyproject.toml, python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/test_instrumentor.py, python/instrumentation/openinference-instrumentation-autogen/pyproject.toml, python/instrumentation/openinference-instrumentation-bedrock/pyproject.toml, python/instrumentation/openinference-instrumentation-bedrock/tests/test_instrumentor.py, python/instrumentation/openinference-instrumentation-crewai/pyproject.toml, python/instrumentation/openinference-instrumentation-crewai/tests/openinference/instrumentation/crewai/test_instrumentor.py, python/instrumentation/openinference-instrumentation-dspy/pyproject.toml, python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py, python/instrumentation/openinference-instrumentation-groq/pyproject.toml, python/instrumentation/openinference-instrumentation-groq/tests/test_instrumentor.py, python/instrumentation/openinference-instrumentation-guardrails/pyproject.toml, python/instrumentation/openinference-instrumentation-guardrails/tests/openinference/instrumentation/guardrails/test_instrumentor.py, python/instrumentation/openinference-instrumentation-haystack/pyproject.toml, python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/test_instrumentor.py, python/instrumentation/openinference-instrumentation-instructor/pyproject.toml, python/instrumentation/openinference-instrumentation-instructor/tests/openinference/instrumentation/instructor/test_instrumentation.py, python/instrumentation/openinference-instrumentation-langchain/pyproject.toml, python/instrumentation/openinference-instrumentation-langchain/tests/test_instrumentor.py, python/instrumentation/openinference-instrumentation-litellm/pyproject.toml, python/instrumentation/openinference-instrumentation-litellm/tests/test_instrumentor.py, python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml, python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_instrumentor.py, python/instrumentation/openinference-instrumentation-mistralai/pyproject.toml, python/instrumentation/openinference-instrumentation-mistralai/tests/openinference/instrumentation/mistralai/test_instrumentor.py, python/instrumentation/openinference-instrumentation-openai/pyproject.toml, python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/test_instrumentor.py, python/instrumentation/openinference-instrumentation-vertexai/pyproject.toml, python/instrumentation/openinference-instrumentation-vertexai/tests/test_instrumentor.py
openinference can become automatically enabled with [opentelemetry's zero code approach for python](https://opentelemetry.io/docs/zero-code/python/#configuring-the-agent), by adding entrypoints into the pyproject.toml.
Specifically, after this, as long as you have the dependencies of your main code, plus openinference-instrumentation-XXXX, and env exported with standard variables, if you launch with `opentelemetry-instrument`, traces will magically appear.
```bash
opentelemetry-instrument python main.py
```
I've added this configuration for all instrumentation, similar to smolagents done in #1276. I've also added a unit test as that helps ensure refactorings won't break this later.
=> feat: add entrypoint for use in opentelemetry-instrument

python/.gitignore, python/instrumentation/openinference-instrumentation-smolagents/README.md, python/instrumentation/openinference-instrumentation-smolagents/examples/README.md, python/instrumentation/openinference-instrumentation-smolagents/examples/e2b_example.py, python/instrumentation/openinference-instrumentation-smolagents/examples/env.example, python/instrumentation/openinference-instrumentation-smolagents/examples/managed_agent.py, python/instrumentation/openinference-instrumentation-smolagents/examples/openai_model.py, python/instrumentation/openinference-instrumentation-smolagents/examples/openai_model_tool_call.py, python/instrumentation/openinference-instrumentation-smolagents/examples/rag.py, python/instrumentation/openinference-instrumentation-smolagents/examples/requirements.txt, python/instrumentation/openinference-instrumentation-smolagents/examples/text2sql.py, python/instrumentation/openinference-instrumentation-smolagents/examples/tool_calling_agent.py, python/instrumentation/openinference-instrumentation-smolagents/examples/tool_invocation.py, python/instrumentation/openinference-instrumentation-smolagents/tests/openinference/instrumentation/smolagents/test_instrumentor.py
This update smolagents code where recent versions drifted:
* [remove of `ManagedAgent`](https://github.com/huggingface/smolagents/pull/484)
* [removal of `max_tokens` from all models](https://github.com/huggingface/smolagents/pull/475)
This also polishes the examples directory and adds a README there, some of the notable changes below:
* use `opentelemetry-instrument`, so that you can easily copy/paste examples without needing to edit in instrumentation
* remove explicit code that is the same as openai default behavior
* add env.example to document important settings that apply to main or otel code
* added missing tests for `opentelemetry-instrument` entrypoint and `._tracer` is a `OITracer`
I can do make the main README, use opentelemetry-instrument, too if this seems alright.
=> feat(smolagents): updates to latest and makes examples use opentelemetry-instrument

python/instrumentation/openinference-instrumentation-haystack/pyproject.toml, python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/__init__.py, python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/_wrappers.py, python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/cassettes/test_instrumentor/test_cohere_reranker_span_has_expected_attributes.yaml, python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/test_instrumentor.py
Updates to `haystack-ai==2.10` make it difficult to rely on `Pipeline._run_component` in the way we were previously. This PR instead dynamically instruments haystack component run methods at the time they are invoked. Due to the way Haystack defines components dynamically using metaclasses, it's difficult to do this once at the moment `instrument` is invoked.
=> fix(haystack): update haystack for compatibility with 2.10

python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py, python/instrumentation/openinference-instrumentation-langchain/tests/test_instrumentor.py
=> fix: message content when it's list of strings

js/packages/openinference-instrumentation-langchain/examples/README.md
This pull request includes a minor change to the `README.md` file in the `openinference-instrumentation-langchain` package. The change corrects the markdown syntax for a hyperlink.
* [`js/packages/openinference-instrumentation-langchain/examples/README.md`](diffhunk://#diff-68ef0879481fe64fa44fed107e0c483995c8ff8fce1e447ad155f9fbbfa4aff5L7-R7): Fixed the markdown syntax for the Phoenix server link.
=> docs(langchain.js): fix formatting

js/.changeset/rude-turkeys-search.md, js/packages/openinference-instrumentation-openai/src/instrumentation.ts, js/packages/openinference-instrumentation-openai/test/openai.test.ts
The js openai image attribute path is different from python, and only the python version works.
- js: see test change in pull request
- python: https://github.com/Arize-ai/openinference/blob/main/python/instrumentation/openinference-instrumentation-langchain/tests/test_image_in_message.py#L46
Tested by calling `ts-node` on `js/packages/openinference-instrumentation-openai/examples/manual-instrumentation.ts` with the following change:
```
client.chat.completions
.create({
model: "gpt-3.5-turbo",
messages: [{ role: "system", content: "You are a helpful assistant." }],
max_tokens: 150,
temperature: 0.5,
})
.then((response) => {
// eslint-disable-next-line no-console
console.log(response.choices[0].message.content);
});
```
-> 
```
client.chat.completions
.create({
model: "gpt-4o-mini", …
```
=> fix: fix js openai image attribute path

js/.changeset/plain-poems-lick.md, js/packages/openinference-instrumentation-beeai/package.json, js/packages/openinference-instrumentation-beeai/src/helpers/getSerializedObjectSafe.ts, js/pnpm-lock.yaml
The instrumentation module does not exist in the beeai framework yet. I needed to remove `instrumentationLogger` imported from this deprecated / removed module.
=> fix(beeai): remove deprecated instrumentation logger

python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/_processor.py
resolves #1397
Unfortunately, `TOOL_DESCRIPTION` and `TOOL_PARAMETERS` are not readily available.
=> fix: add span attributes for FunctionSpanData

python/openinference-instrumentation/src/openinference/instrumentation/_spans.pyi, python/openinference-instrumentation/src/openinference/instrumentation/_tracers.py, python/openinference-instrumentation/tests/test_config.py
The implementation of `openinference.instrumentation.OpenInferenceSpan` using `wrapt.ObjectProxy` doesn't preserve type hints for the methods of the wrapped OTel span. This means `mypy` doesn't know about these methods and language servers can't suggest methods on our span type.
resolves #1377
=> fix: add type stubs for openinference span

js/.changeset/bumpy-breads-look.md, js/packages/openinference-instrumentation-beeai/src/helpers/getSerializedObjectSafe.ts, js/packages/openinference-instrumentation-beeai/src/middleware.ts
The serialisation process works when the memory object or some other data is missing. 
In the second commit [3ba99bad78b0b95a600e5f70680da08e06f37aa3](https://github.com/Arize-ai/openinference/pull/1425/commits/3ba99bad78b0b95a600e5f70680da08e06f37aa3) I only wrapped the whole `getSerializedObjectSafe` method in try/catch block. Git generated more changes, but there are not more changes. 
in the third commit [4ecc1b3931cb924e6616731a7de6949fe0f31acb](https://github.com/Arize-ai/openinference/pull/1425/commits/4ecc1b3931cb924e6616731a7de6949fe0f31acb) I only wrapped the emitter callbacks in try/catch block as well.
=> fix(beeai): empty data serialization

python/examples/dspy-rag-fastapi/backend/app/utils/rag_functions.py, python/examples/dspy-rag-fastapi/backend/instrument.py, python/examples/dspy-rag-fastapi/backend/poetry.lock, python/examples/dspy-rag-fastapi/backend/pyproject.toml, python/examples/dspy-rag-fastapi/frontend/pages/1_zero_shot_query.py, python/examples/dspy-rag-fastapi/frontend/pages/2_compiled_query.py, python/examples/dspy-rag-fastapi/frontend/pages/3_optimize_pipeline.py
I've fixed the tracing issues in the DSPy RAG FastAPI example.
**Phoenix Traces**
**Application Working (zero shot query)**
**Application Working (compiled query)**
Resolves #1364
=> fix: Tracing Issues in DSPy RAG FastAPI Example

python/instrumentation/openinference-instrumentation-smolagents/src/openinference/instrumentation/smolagents/__init__.py
When working with a smolagents library of the `main` branch you would typically get something like:
```
DependencyConflict: requested: "smolagents >= 1.2.2" but found: "smolagents 1.13.0.dev0"
```
I understand that technically you can use flag:
```py
SmolagentsInstrumentor().instrument(skip_dep_check=True)
```
However maybe it would have been easier just to allow prerelease versions by default? 1.13.0.dev0 >= 1.2.2 satisfies the constraint in my opinion :)
ref. https://github.com/huggingface/smolagents/blob/main/pyproject.toml#L7
=> fix: allow prerelease versions of smolagents

python/openinference-instrumentation/src/openinference/instrumentation/_attributes.py
=> fix: ensure io attributes output by manual instrumentation helpers are always strings

python/instrumentation/openinference-instrumentation-anthropic/pyproject.toml, python/instrumentation/openinference-instrumentation-autogen/pyproject.toml, python/instrumentation/openinference-instrumentation-bedrock/pyproject.toml, python/instrumentation/openinference-instrumentation-crewai/pyproject.toml, python/instrumentation/openinference-instrumentation-dspy/pyproject.toml, python/instrumentation/openinference-instrumentation-groq/pyproject.toml, python/instrumentation/openinference-instrumentation-guardrails/pyproject.toml, python/instrumentation/openinference-instrumentation-haystack/pyproject.toml, python/instrumentation/openinference-instrumentation-instructor/pyproject.toml, python/instrumentation/openinference-instrumentation-langchain/pyproject.toml, python/instrumentation/openinference-instrumentation-litellm/pyproject.toml, python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml, python/instrumentation/openinference-instrumentation-mistralai/pyproject.toml, python/instrumentation/openinference-instrumentation-openai-agents/pyproject.toml, python/instrumentation/openinference-instrumentation-openai/pyproject.toml, python/instrumentation/openinference-instrumentation-smolagents/pyproject.toml, python/instrumentation/openinference-instrumentation-vertexai/pyproject.toml
Ensures all packages have updated attribute getters
=> fix: increased minimum supported version of openinference-instrumentation to 0.1.27

js/.changeset/some-dots-greet.md, js/packages/openinference-instrumentation-langchain/src/utils.ts
If a langchain message history contained tool messages, it would blow up instrumented results into a big blob of json. Now they render properly in the UI.
=> feat(langchain-js): Instrument langchain tool messages

js/.changeset/many-olives-cross.md, js/packages/openinference-instrumentation-langchain/src/tracer.ts
example span
```
{
resource: {
attributes: {
model_id: 'lc----test---parker',
model_version: 'your-model-version'
}
},
instrumentationScope: {
name: '@arizeai/openinference-instrumentation-langchain',
version: '3.1.0',
schemaUrl: undefined
},
traceId: '76ab36f9d8eb47a85b5bc9ead7ff5ea8',
parentSpanContext: undefined,
traceState: undefined,
name: 'ChatOpenAI',
id: '704252597a1253ac',
kind: 0,
timestamp: 1744670835353000,
duration: 233380.375,
attributes: {
'openinference.span.kind': 'LLM',
'input.value': '{"messages":[[{"lc":1,"type":"constructor","id":["langchain_core","messages","AIMessage"],"kwargs":{"tool_calls":[{"name":"test-tool","args":{"test-arg":"test-value"},"id":"test-tool-call-id"}],"content":"test-content","invalid_tool_calls":[],"additional_kwargs":{},"response_metadata":{}}}] …
```
=> fix: record exceptions for on spans

js/.changeset/pink-pillows-carry.md, js/packages/openinference-instrumentation-mcp/README.md, js/packages/openinference-instrumentation-mcp/jest.config.js, js/packages/openinference-instrumentation-mcp/package.json, js/packages/openinference-instrumentation-mcp/src/index.ts, js/packages/openinference-instrumentation-mcp/src/mcp.ts, js/packages/openinference-instrumentation-mcp/test/collector.ts, js/packages/openinference-instrumentation-mcp/test/mcp.test.ts, js/packages/openinference-instrumentation-mcp/test/mcpserver.ts, js/packages/openinference-instrumentation-mcp/tsconfig.esm.json, js/packages/openinference-instrumentation-mcp/tsconfig.esnext.json, js/packages/openinference-instrumentation-mcp/tsconfig.json, js/pnpm-lock.yaml
This is the JS version of #1524.
/cc @codefromthecrypt
=> feat: mcp js context propagation

python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/_processor.py
Closes #1423
---
It seems that there are no instrumentation tests implemented and a unit test for `_get_span_status` felt 🤷 as the important change is the `on_span_end` usage.
I tested this manually:
```py
from agents import Agent, Runner, function_tool
from openinference.instrumentation.openai_agents import OpenAIAgentsInstrumentor
from opentelemetry.sdk import trace as trace_sdk
from opentelemetry.sdk.trace.export import ConsoleSpanExporter, SimpleSpanProcessor
tracer_provider = trace_sdk.TracerProvider()
tracer_provider.add_span_processor(SimpleSpanProcessor(ConsoleSpanExporter()))
@function_tool
def search_web(query: str) -> str:
"""A tool that can be used to search the web."""
raise ValueError("It's a trap!")
OpenAIAgentsInstrumentor().instrument(tracer_provider=tracer_provider) …
```
=> fix(openai_agents): Set status `on_span_end`.

python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/__init__.py, python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/middleware.py, python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/utils/get_serialized_object_safe.py
Currently, if you run beeai with this instrumentation, you'll get '2' printed to the console occasionally.
This removes the spurious 2 and converts the rest of the prints to log errors per style in otel. https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-botocore/src/opentelemetry/instrumentation/botocore/__init__.py#L383
cc @GALLLASMILAN @mikeldking
p.s. most otel instrumentation do not do a lot of defensive catching of errors. once the dust settles, another PR might be wise to remove some of this.
=> fix: removes spurious print(2) from python beeai and converts rest to loggers

python/instrumentation/openinference-instrumentation-litellm/src/openinference/instrumentation/litellm/__init__.py
resolves: https://github.com/Arize-ai/openinference/issues/1318
Start the span before we call the original llitellm funcs in order to properly instrument and capture the latency
Before:
After:
=> fix: Start span before API call

python/instrumentation/openinference-instrumentation-litellm/src/openinference/instrumentation/litellm/__init__.py, python/instrumentation/openinference-instrumentation-litellm/tests/cassettes/TestTokenCounts.test_openai.yaml, python/instrumentation/openinference-instrumentation-litellm/tests/test_instrumentor.py, python/instrumentation/openinference-instrumentation-litellm/tests/test_token_counts.py
resolves: #1559 - remove and only remove api_key from invocation_params
=> fix(litellm): remove sensitive info from invocation params

python/dev-requirements.txt, python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/utils/anthropic/_messages.py, python/instrumentation/openinference-instrumentation-bedrock/tests/openinference/instrumentation/bedrock/test_invoke_agent_instrumentor.py, python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/_wrappers.py, python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/_processor.py, python/instrumentation/openinference-instrumentation-openai/pyproject.toml, python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_attributes/_responses_api.py, python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/test_instrumentor.py
Recently, Ruff was upgraded from **v0.6.1** to **v0.9.2** in the project.
This upgrade introduced stricter formatting and linting rules, which caused some of the existing instrumentation code to fail Ruff checks.
This merge request addresses those issues by:
* Fixing all Ruff formatting violations where possible.
* Adding `# type: ignore` comments in cases where the formatting or type issues could not be cleanly resolved.
* Aligned code formatting to comply with Ruff v0.9.1 rules.
* Suppressed type errors using `# type: ignore` where necessary, particularly in complex TypedDict or type-checking scenarios.
* Ensured all modified files pass Ruff and mypy checks post-change.
Closes https://github.com/Arize-ai/openinference/issues/1594
=> fix: ruff formating fix & bump ruff version in dev requirements

python/instrumentation/openinference-instrumentation-google-genai/README.md
Fix a small syntax error in the docs.
```
from openinference.instrumentation.google-genai import GoogleGenAIInstrumentor
^
SyntaxError: invalid syntax
```
It should be `google_genai`
=> docs: fix google genai import in README

python/instrumentation/openinference-instrumentation-agno/examples/basic_agent_with_tools.py, python/instrumentation/openinference-instrumentation-agno/src/openinference/instrumentation/agno/__init__.py, python/instrumentation/openinference-instrumentation-agno/tests/test_instrumentor.py
There is a bug in Agno instrumentation that causes duplicate model traces to be produced.
Fixes #1613
=> fix: Agno duplicate model invoke

python/instrumentation/openinference-instrumentation-dspy/examples/tools.py, python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py, python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/cassettes/test_instrumentor/test_react[False].yaml, python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/cassettes/test_instrumentor/test_react[True].yaml, python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
Continuing #1581: This PR adds tracing for DSPy.Tool. 
This was more involved than I originally thought. I could have directly tested tools and been done with it, but ReAct is a core building block in DSPy, so I figured I'd get a solid test around a simple run of that. 
I've confirmed that ci tox jobs are passing both under 3.9 and 3.13 :smile: :rocket:
=> feat(dspy): Instrument DSPy.Tool

python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/__init__.py, python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/_processor.py
[set_trace_processors()](https://openai.github.io/openai-agents-python/ref/tracing/#agents.tracing.set_trace_processors)
`add_trace_processor` continues to use OpenAI's tracing 
leading to `OPENAI_API_KEY is not set, skipping trace export` warnings
changes allow for Phoenix to be used seperately from Openai's API without warnings/errors.
Being able to use phoenix-otel's [register](https://github.com/Arize-ai/phoenix/blob/a6e523a20b73170a0bdb816a8b8f5c1303426126/packages/phoenix-otel/src/phoenix/otel/otel.py#L64) function, and have it exclusively export traces to phoenix would be ideal.
https://docs.arize.com/phoenix/tracing/integrations-tracing/openai-agents-sdk
```py
from agents import (
Agent,
OpenAIChatCompletionsModel,
Runner,
set_default_openai_client,
)
from openai import …
```
=> feat(openai-agents): add support for exclusive processor configuration

python/instrumentation/openinference-instrumentation-mcp/pyproject.toml, python/instrumentation/openinference-instrumentation-mcp/src/openinference/instrumentation/mcp/__init__.py, python/instrumentation/openinference-instrumentation-mcp/test-requirements.txt
fixes #1616 
This PR updates openinference-instrumentation-mcp to be compatible with mcp>=1.8.0, which introduced a breaking change in the message format. The new version wraps the `JSONRPCRequest` inside a `SessionMessage`, requiring instrumentation logic to be updated accordingly.
- mcp is upgraded from 1.6.0 → 1.8.0 in both pyproject.toml and test-requirements.txt.
- Wrapped messages are now unwrapped via SessionMessage.message.root to extract the original `JSONRPCRequest`.
- Compatibility logic updated in both the `__aiter__` and `send()` paths.
Without this change, context injection and extraction fail because the instrumentation attempts to unwrap the wrong type (JSONRPCMessage instead of SessionMessage). This causes runtime errors in tracing environments when used with mcp >= …
=> fix(mcp): support mcp>=1.8.0 with new SessionMessage structure

python/instrumentation/openinference-instrumentation-mcp/pyproject.toml, python/instrumentation/openinference-instrumentation-mcp/src/openinference/instrumentation/mcp/__init__.py, python/instrumentation/openinference-instrumentation-mcp/test-requirements.txt, python/instrumentation/openinference-instrumentation-mcp/tests/mcpserver.py, python/instrumentation/openinference-instrumentation-mcp/tests/test_instrumenter.py
Prior to this PR, OpenInference’s MCP instrumentation only covered STDIO and SSE transports, leaving calls over the newer Streamable-HTTP unmonitored. To enable context propagation for Streamable-HTTP, we’ve added a dedicated wrapper that correctly handles its three-tuple API. While developing tests against mcp v1.8.0, we uncovered a deadlock in the Streamable-HTTP implementation; upgrading the dependency to mcp ≥ 1.8.1 pulls in the upstream fix ([v1.8.1 release notes](https://github.com/modelcontextprotocol/python-sdk/releases/tag/v1.8.1)) and ensures our new wrapper operates without hanging.
1. Upgrade mcp requirement from >=1.8.0 to >=1.8.1
2. Instrumentation hooks (`__init__.py`)
- **Streamable-HTTP client**: wrap `mcp.client.streamable_http.streamablehttp_client` with …
=> feat(mcp): add instrumentation support for Streamable-HTTP transport and bump mcp dependency to ≥1.8.1

spec/semantic_conventions.md
Adds documentation and some examples of what you might want to use to fill out the semantic conventions around prompts that sit on a server.
The idea here is that some clients (like portkey, brantrust) only know about the prompt_id, nothing else. The spans emitted when invoking these clients should have the identifier of the prompt over which they are performing synthesis.
=> docs: add documentation about prompt semantic conventions

python/instrumentation/openinference-instrumentation-portkey/src/openinference/instrumentation/portkey/__init__.py, python/instrumentation/openinference-instrumentation-portkey/src/openinference/instrumentation/portkey/_request_attributes_extractor.py, python/instrumentation/openinference-instrumentation-portkey/tests/cassettes/test_prompt_template.yaml, python/instrumentation/openinference-instrumentation-portkey/tests/test_instrumentor.py
Resolves #1573 
If prompt_id and prompt_variables are present in the invocation params it maps them to the span attributes prompt_id and llm.prompt_template.variables. Also wraps a the Prompt.completions function in the existing completion wrapper to ensure those spans are created.
Screenshots below
=> feat(portkey): Add support for propmt template calls

python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
In the recent release of dspy [v2.6.24](https://github.com/stanfordnlp/dspy/releases/tag/2.6.24), the default maximum token count was increased from 1000 to 4000. Our unit tests currently validate against the previous default of 1000, causing them to fail under the new version.
This merge request updates the affected test cases to align with the new default token limit introduced in [this PR](https://github.com/stanfordnlp/dspy/pull/8215), ensuring compatibility with the latest release of dspy.
Closes https://github.com/Arize-ai/openinference/issues/1692
=> fix(dspy): upstream max token default value change

python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/__init__.py, python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/_wrappers.py, python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/test_instrumentor.py
This PR resolves all `mypy` errors shown in the GitHub CI output, even though many of those specific errors do not appear in my local environment with a fresh project setup. Most issues were related to missing type hints in `haystack` submodules, so I added appropriate `# type: ignore` comments to prevent CI failures and ensure consistent type-checking across environments.
Closes #1691
=> fix: CI Failures For Haystack

python/instrumentation/openinference-instrumentation-agno/src/openinference/instrumentation/agno/_wrappers.py
- fixes: https://github.com/agno-agi/agno/issues/3273
- if we pass sensitive params like `api_key`, `api_base` etc in the Agno `Model` config, its being tracked and shown in otel platforms.
- This PR marks such sensitive info as `REDACTED`
=> fix: filter sensitive model params

python/instrumentation/openinference-instrumentation-litellm/src/openinference/instrumentation/litellm/__init__.py, python/instrumentation/openinference-instrumentation-litellm/tests/test_instrumentor.py
**Issue**: fixes #1721
**Description**:
This PR replaces plain text output (from assistant message) with full JSON model output for litellm completions and updates tests accordingly. Output messages are displayed as previously
**Before**:
**After**:
=> fix(litellm): full JSON output

js/.changeset/stale-gifts-teach.md, js/packages/openinference-instrumentation-openai/README.md, js/packages/openinference-instrumentation-openai/examples/responses.ts, js/packages/openinference-instrumentation-openai/package.json, js/packages/openinference-instrumentation-openai/src/instrumentation.ts, js/packages/openinference-instrumentation-openai/test/openai.responses.test.ts, js/packages/openinference-instrumentation-openai/test/openai.test.ts, js/pnpm-lock.yaml
We now maintain the response contract at the end of openai method invocations, allowing the openai sdk to chain method calls that have been instrumented by arize instrumentation.
As a result, the `parse` methods, which relied on chaining, work correctly.
resolves #1799
=> feat(openai): Add support for chat.parse and responses.parse

js/.changeset/shiny-clouds-join.md, js/packages/openinference-vercel/package.json, js/pnpm-lock.yaml
Our vercel instrumentation sometimes would work with next js projects or vercel/otel packages for some project setups but would mysteriously not work for others.
It turns out that some package managers would not be able to resolve the same version of opentelemetry/api in this package that the vercel ai package hard pins, meaning that the ai sdk would sometimes send traces into the ether, using the wrong global tracer provider.
Opening up the version range to the same that ai sdk pins, seems to resolve to a single API package instance, ensuring that there is only one tracer provider registered globally.
=> fix(openinference-vercel): Bump package ranges

python/instrumentation/openinference-instrumentation-smolagents/src/openinference/instrumentation/smolagents/_wrappers.py
This PR improves observability of handled (non-fatal) errors in multi-step `smolagents` execution by adding a minimal structured event (`agent.step_recovery`) to the span when an `AgentError` occurs in `_StepWrapper`. Instead of recording the `exception` or marking the span as failed, it attaches the error `type` & `message` using `step_log.error.dict()`, enabling Arize & Phoenix to display soft failures clearly without triggering red-flash-bad-error states. This ensures better trace visibility for recoverable agent behavior while maintaining clean, successful span statuses.
Closes #1198
=> feat(smolagents): Improve Display Of Handled Errors

.github/workflows/typescript-CI.yaml, js/.changeset/hot-terms-hide.md, js/examples/langchain-express/frontend/app/globals.css, js/examples/llama-index-express/frontend/app/globals.css, js/examples/next-openai-telemetry-app/app/globals.css, js/examples/openai/frontend/app/globals.css, js/package.json, js/packages/openinference-vercel/src/utils.ts, js/packages/openinference-vercel/test/OpenInferenceSpanProcessor.test.ts, js/pnpm-lock.yaml
Prevent `openinference.span.kind` from being overwritten if already set.
This fixes #1856 where the `openinference-vercel` package would incorrectly overwrite an existing `openinference.span.kind` attribute.
=> fix(vercel): span processor should not override existing span kind

python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/_processor.py, python/instrumentation/openinference-instrumentation-openai-agents/tests/test_span_attribute_helpers.py
If a function returns an empty string, `_get_attributes_from_function_span_data` will raise an IndexError - https://github.com/Arize-ai/openinference/blob/4645932b68f7ed5ab3ecd8818ddad9e1011c027e/python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/_processor.py#L459
=> fix: fix IndexError for empty function output

js/.changeset/empty-pianos-stay.md, js/packages/openinference-instrumentation-beeai/examples/instrumentation.ts, js/packages/openinference-instrumentation-beeai/src/instrumentation.ts, js/packages/openinference-instrumentation-langchain/src/instrumentation.ts, js/packages/openinference-instrumentation-langchain/test/langchainV2.test.ts, js/packages/openinference-instrumentation-langchain/test/langchainV3.test.ts, js/packages/openinference-instrumentation-openai/src/instrumentation.ts, js/packages/openinference-instrumentation-openai/test/openai.test.ts
resolve #1837 
- adds options traceProvider param to langchain, beeai, and openai instrumentations to allow the tracer to be pulled from the passed in trace provider instead of the global one
=> feat: add support for non global trace provider in instrumentations

python/openinference-instrumentation/src/openinference/instrumentation/_capture.py, python/openinference-instrumentation/tests/test_context_managers.py
resolves #2011 
```python
from openinference.instrumentation import capture_span_context
from phoenix.client import Client
client = Client()
chat_engine = [index.as](http://index.as/)_chat_engine()
with capture_span_context() as capture:
chat_engine.chat("Hello?")
first_span_id = capture.get_first_span_id()
print(first_span_id)
if last_span_id:
client.annotations.add_span_annotation(
annotation_name="user_feedback",
annotator_kind="HUMAN",
span_id=first_span_id,
label="my_label",
score=1,
explanation="just because"
)
```
=> feat(python): get_first_span_id via a context manager

python/instrumentation/openinference-instrumentation-openai-agents/pyproject.toml
resolves: #2005 
TypeError when using str | None union syntax in openai-agents library on Python 3.9. The eval_type_backport package automatically converts modern union syntax to compatible typing.Union forms.
=> fix: openai-agents CI add eval_type_backport dependency for Python <3.10 compatibility

spec/README.md, spec/configuration.md, spec/embedding_spans.md, spec/llm_spans.md, spec/multimodal_attributes.md, spec/semantic_conventions.md, spec/tool_calling.md
I updated [Envoy AI Gateway to use OpenInference for its tracing](https://aigateway.envoyproxy.io/docs/0.3/capabilities/observability/tracing/) format. As a part of that, I captured the behavior of the latest Python OpenAI instrumentation and ported it to Go (the gateway process is Go).
While there are a lot of changes here, I think it is best to update as it will make it easier for the next person or agent who tries to implement this with the spec. I'm very flexible in the amount of change, so if you want things removed or re-organized, just say it!
If you want to read about how this works, consider [this](https://tetrate.io/blog/opentelemetry-tracing-arrives-in-envoy-ai-gateway) click bait ;)
=> docs: converge spec to Python OpenAI practice

python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
**TL;DR:** This fixes the Langchain instrumentor not picking up token details sometimes.
**Long version:**
I've tried to use Phoenix Arize to trace my Langgraph agent, but found that it does not capture cached tokens, even though the token details are present in `output` of LLM spans.
The investigation led me to [Langchain tracer](https://github.com/Arize-ai/openinference/blob/main/python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py), where I found that it is only suited for a handful of LLM providers (OpenAI, Gemini and Anthropic), and doesn't even attempt to work with Langchain's abstractions like the [`UsageMetadata`](https://python.langchain.com/api_reference/core/messages/langchain_core.messages.ai.UsageMetadata.html#la …
=> fix(Langchain): map UsageMetadata object

python/instrumentation/openinference-instrumentation-instructor/src/openinference/instrumentation/instructor/_wrappers.py, python/instrumentation/openinference-instrumentation-instructor/tests/openinference/instrumentation/instructor/test_instrumentation.py
This PR fixes an issue where setting `max_retries` as a `tenacity.Retrying` object caused `JSON` serialization errors in span attributes. The update ensures non-serializable objects are handled safely so traces can be sent without breaking. It also adds explicit `StatusCode.OK` on successful runs, making traces clearer and easier to follow in Arize & Phoenix.
**Instructor Trace**
Closes #1569
=> fix(instructor): JSON Serialization Error for max_retries in Span Attributes

README.md, python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request.py, python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request_attributes_extractor.py, python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_response_attributes_extractor.py, python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_utils.py, python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/test_instrumentor.py
This PR aligns openai with the specification changes around embeddings in #2162 
**Spec changes from 2162**
- Consistent span name: `"CreateEmbeddings"`
- Standardized attribute structure: `embedding.embeddings.N.embedding.{text|vector}`
- Unified invocation parameter tracking: `embedding.invocation_parameters`
- Proper `llm.system` attribute for provider identification
**Code improvements:**
- Full batch embedding support with indexed attributes
- Separated invocation parameters from input data
- Improved handling of token IDs vs text inputs
=> feat(openai): align embedding instrumentation with pending spec
