- js/.changeset/old-apples-attack.md
- js/packages/openinference-instrumentation-openai/CHANGELOG.md
- js/packages/openinference-instrumentation-openai/package.json
- js/packages/openinference-semantic-conventions/CHANGELOG.md
- js/packages/openinference-semantic-conventions/package.json
Reverts Arize-ai/openinference#42
> Revert "chore(js): update versions"

- js/package.json
- chore: change publish script for JS
- change package.json
> chore(js): change build and publish script

- python/openinference-semantic-conventions/tests/openinference/semconv/test_version.py
"no test ran" has an exit code of 5. This PR adds dummy test to make testing in CI easier.
> chore: add dummy test for semantic conventions

- .github/workflows/typescript-CI.yaml
- js/packages/openinference-semantic-conventions/package.json
resolves #28
Enforces tests across all js repos.
> ci(js): enforce tests in CI

- python/DEVELOPMENT.md
> chore(python): add DEVELOPMENT.md

- js/DEVELOPMENT.md
- js/README.md
resolves #32 
Adds a development guide for the JS mono-repo
> docs(js): development guide

- js/.changeset/short-forks-speak.md
- js/.eslintrc.js
- js/examples/openai/src/index.ts
- js/packages/openinference-instrumentation-openai/src/instrumentation.ts
- js/packages/openinference-instrumentation-openai/src/typeUtils.ts
- js/packages/openinference-instrumentation-openai/test/openai.test.ts
resolves #114 
Adds support for function and tool calls invoked during streaming for openai
> feat(js): openai tool and function call support on streaming

- js/examples/llama-index-express/README.md
- js/examples/llama-index-express/backend/Dockerfile
- js/examples/llama-index-express/backend/package.json
- js/examples/llama-index-express/compose.yml
- js/examples/llama-index-express/frontend/Dockerfile
- js/examples/llama-index-express/frontend/next.config.js
- use production builds for docker
- use multistage builds
> chore(js): set up productionized builds for docker compose

- release-please-config.json
- chore: move py.typed for dspy
- fix-release-please
> chore: move py typed

- README.md
- python/instrumentation/openinference-instrumentation-bedrock/README.rst
- release-please-config.json
> chore: Update READMEs to include Bedrock instrumentor and add Bedrock to release-please

- README.md
- add links to examples
- add supported destinations
- add community section
> docs: add examples, supported destinations, and community links to readme

- js/.changeset/cuddly-shoes-beg.md
- js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
- python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py
- spec/semantic_conventions.md
Reverts Arize-ai/openinference#176
> Revert "feat(semcov): add metadata"

- python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
resolves https://github.com/Arize-ai/openinference/issues/184
> py38-ci-langchain-latest: OK ✔ in 1 minute 20.04 seconds
> py311-ci-langchain-latest: OK ✔ in 1 minute 16.21 seconds
> fix(python): parent id for async in langchain-core 0.1.21

- python/instrumentation/openinference-instrumentation-langchain/examples/chain_metadata.py
- python/instrumentation/openinference-instrumentation-langchain/examples/openai_chat_stream.py
- python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
- python/instrumentation/openinference-instrumentation-langchain/tests/openinference/instrumentation/langchain/test_instrumentor.py
resolves https://github.com/Arize-ai/openinference/issues/191
> fix: set langchain template variables as dict

- cspell.json
- js/packages/openinference-instrumentation-llama-index/README.md
- js/packages/openinference-instrumentation-llama-index/jest.config.js
- js/packages/openinference-instrumentation-llama-index/package.json
- js/packages/openinference-instrumentation-llama-index/test/llamaIndex.test.ts
- js/packages/openinference-instrumentation-llama-index/tsconfig.esm.json
- js/packages/openinference-instrumentation-llama-index/tsconfig.esnext.json
- js/packages/openinference-instrumentation-llama-index/tsconfig.json
- js/pnpm-lock.yaml
resolves #195 
Scaffolds the LlamaIndex.TS instrumentor package
> feat(llamaindex): scaffold LlamaIndex.TS instrumentor package

- python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
> fix: handle BaseException

- python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
> fix: replace NaN with none in output JSON

- python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/__init__.py
> fix: avoid llama-index dependency at import time

- python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_callback.py
- python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_callback.py
resolves #236
Added a description string alongside the span status code when an exception occurs.
The description is formatted in the same way as the OTEL SDK as seen [here](https://github.com/open-telemetry/opentelemetry-python/blob/2b9dcfc5d853d1c10176937a6bcaade54cda1a31/opentelemetry-api/src/opentelemetry/trace/__init__.py#L588), i.e. 
```python
f"{type(exception).__name__}: {exception}"
```
> feat: add status description to llama-index instrumentor

- python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_callback.py
> fix: allow instrumentation to be suppressed in llama-index instrumentor

- python/instrumentation/openinference-instrumentation-dspy/pyproject.toml
- python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py
- python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
A recent DSPy release broke the way we parse output fields. This fixes that issue.
> fix: support dpsy 2.3.4 and above

- python/instrumentation/openinference-instrumentation-dspy/pyproject.toml
- python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py
- python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
- adds support for DSPY's `Google` LLM class
> fix: add support for DSPy's Google model class

- python/openinference-semantic-conventions/src/openinference/semconv/resource/__init__.py
resolves https://github.com/Arize-ai/phoenix/issues/2381
> feat: add resource attributes to semantic conventions

- python/examples/langserve/per_request_metadata.py
resolves: https://github.com/Arize-ai/phoenix/issues/2418
> chore: add example for langserve

- python/instrumentation/openinference-instrumentation-llama-index/README.md
> docs: quick start demo for llama-index

- python/instrumentation/openinference-instrumentation-bedrock/README.md
> docs: Improve README

- python/instrumentation/openinference-instrumentation-openai/README.md
> docs(openai): flesh out README

- python/instrumentation/openinference-instrumentation-dspy/README.md
- adds quickstart and links to dspy readme
resolves #267
> docs: improve dspy readme

- python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
also added a lock to protect the dict
> fix: allow running handler in threads

- .release-please-manifest.json
For the first release of the package.
> chore: add mistralai to release-please manifest

- python/instrumentation/openinference-instrumentation-mistralai/tests/openinference/instrumentation/openai/test_instrumentor.py
Adds test case to cover the case of an error for synchronous chat completions for Mistral instrumentation.
resolves #299
> chore: add test case for sync chat completions

- python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_chat_wrapper.py
- python/instrumentation/openinference-instrumentation-mistralai/tests/openinference/instrumentation/mistralai/test_instrumentor.py
> fix: mistral argument parsing error

- python/instrumentation/openinference-instrumentation-mistralai/examples/chat_completions_streaming.py
- python/instrumentation/openinference-instrumentation-mistralai/pyproject.toml
- python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/__init__.py
- python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_chat_wrapper.py
- python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_response_accumulator.py
- python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_response_attributes_extractor.py
- python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_stream.py
- python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_utils.py
- python/instrumentation/openinference-instrumentation-mistralai/tests/openinference/instrumentation/mistralai/test_instrumentor.py
> feat: add support for sync streaming to mistralai

- python/instrumentation/openinference-instrumentation-mistralai/examples/chat_completions_async_streaming.py
- python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/__init__.py
- python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_chat_wrapper.py
- python/instrumentation/openinference-instrumentation-mistralai/tests/openinference/instrumentation/mistralai/test_instrumentor.py
adds support async streaming chat completions for `mistralai`.
resolves #317
> feat: support async streaming chat completions for mistralai

- python/instrumentation/openinference-instrumentation-mistralai/examples/chat_completions_streaming_with_function_calling.py
- python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_response_accumulator.py
- python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_response_attributes_extractor.py
- python/instrumentation/openinference-instrumentation-mistralai/tests/openinference/instrumentation/mistralai/test_instrumentor.py
- Adds support for synchronous streaming with function calls
resolves #330
> fix: support streaming with tool calls

- python/DEVELOPMENT.md
> docs: document process for creating a new conda feedstock

- python/openinference-instrumentation/LICENSE
> fix: add license file for openinference-instrumentation

- python/instrumentation/openinference-instrumentation-langchain/README.md
> docs: Update LangChain instrumentation readme

- .github/workflows/typescript-CI.yaml
add CI runs to the feature branch langchainjs
> ci: add langchainjs ci rules

- python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/__init__.py
> fix: Enables `uninstrument` method on `LangchainInstrumentor`

- python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/__init__.py
Fixes formatting and type issues currently causing CI to fail
> fix: fix formatting and types in langchain instrumentation

- js/.eslintrc.js
- js/packages/openinference-instrumentation-langchain/examples/chat.ts
- js/packages/openinference-instrumentation-langchain/examples/chat/chat.ts
- js/packages/openinference-instrumentation-langchain/examples/instrumentation.ts
- js/packages/openinference-instrumentation-langchain/jest.config.js
- js/packages/openinference-instrumentation-langchain/package.json
- js/packages/openinference-instrumentation-langchain/src/index.ts
- js/packages/openinference-instrumentation-langchain/src/instrumentation.ts
- js/packages/openinference-instrumentation-langchain/src/tracer.ts
- js/packages/openinference-instrumentation-langchain/src/typeUtils.ts
- js/packages/openinference-instrumentation-langchain/src/types.ts
- js/packages/openinference-instrumentation-langchain/src/utils.ts
- js/packages/openinference-instrumentation-langchain/test/fixtures.ts
- js/packages/openinference-instrumentation-langchain/test/langchain.test.ts
- js/packages/openinference-instrumentation-langchain/test/utils.test.ts
- js/packages/openinference-instrumentation-langchain/tsconfig.json
- js/pnpm-lock.yaml
- Adds langchainjs instrumentation with support for OpenInference span kind, inputs, outpus
> feat(langchainjs): patch callbacks module add tracer and input / output support

- js/packages/openinference-instrumentation-langchain/package.json
- js/packages/openinference-instrumentation-langchain/src/constants.ts
- js/packages/openinference-instrumentation-langchain/src/tracer.ts
- js/packages/openinference-instrumentation-langchain/src/typeUtils.ts
- js/packages/openinference-instrumentation-langchain/src/types.ts
- js/packages/openinference-instrumentation-langchain/src/utils.ts
- js/packages/openinference-instrumentation-langchain/test/fixtures.ts
- js/packages/openinference-instrumentation-langchain/test/langchain.test.ts
- js/packages/openinference-instrumentation-langchain/test/utils.test.ts
- js/pnpm-lock.yaml
Adds support for
- top level function and tool calling
- prompt templates
- metadata
- token counts
> feat(langchainjs): support top level function and tool calling

- js/.changeset/heavy-elephants-lay.md
- js/packages/openinference-instrumentation-langchain/README.md
- js/packages/openinference-instrumentation-langchain/examples/instrumentation.ts
Updates the readme to reflect the manual instrumentation step to be reflected on npm
> docs(langchainjs): update README to include manual instrumentation step

- js/examples/langchain-express/README.md
- js/examples/langchain-express/backend/index.ts
- js/examples/langchain-express/backend/package-lock.json
- js/examples/langchain-express/backend/package.json
- js/examples/langchain-express/backend/src/constants.ts
- js/examples/langchain-express/backend/src/controllers/chat.controller.ts
- js/examples/langchain-express/backend/src/routes/chat.route.ts
- js/examples/langchain-express/backend/src/types.ts
- js/examples/langchain-express/backend/src/utils.ts
- js/examples/langchain-express/backend/src/vector_store/store.ts
- js/examples/langchain-express/frontend/app/components/chat-section.tsx
- js/examples/langchain-express/frontend/app/components/ui/chat/chat-input.tsx
Adds rag based example for langchain js auto isntrumentation
> feat(langchainjs): add rag example for LangChain.js auto instrumentation

- python/instrumentation/openinference-instrumentation-dspy/examples/dspy_cohere.py
- python/instrumentation/openinference-instrumentation-dspy/examples/dspy_mistral.py
- python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py
resolves #405 
Leverages Cohere's pedantic capabilities to serialize the model output
> fix(dspy): dspy.Cohere

- python/examples/dspy-rag-fastapi/README.md
- python/examples/dspy-rag-fastapi/backend/app/utils/models.py
- python/examples/dspy-rag-fastapi/backend/app/utils/rag_functions.py
- python/examples/dspy-rag-fastapi/backend/poetry.lock
- python/examples/dspy-rag-fastapi/backend/pyproject.toml
- python/examples/dspy-rag-fastapi/compose.yml
- python/examples/dspy-rag-fastapi/frontend/pages/1_zero_shot_query.py
- python/examples/dspy-rag-fastapi/frontend/pages/2_compiled_query.py
- python/examples/dspy-rag-fastapi/frontend/pages/3_optimize_pipeline.py
Adds cohere to the set of models supported. Note the instrumentation is broken for dspy.Cohere right now.
> docs(dspy): add support for cohere

- README.md
- cspell.json
- python/examples/README.md
- python/examples/dspy-rag-fastapi/.gitignore
- python/examples/dspy-rag-fastapi/README.md
- python/examples/dspy-rag-fastapi/backend/Dockerfile
- python/examples/dspy-rag-fastapi/backend/app/api/routers/rag.py
- python/examples/dspy-rag-fastapi/backend/app/utils/load.py
- python/examples/dspy-rag-fastapi/backend/app/utils/models.py
- python/examples/dspy-rag-fastapi/backend/app/utils/rag_functions.py
- python/examples/dspy-rag-fastapi/backend/instrument.py
- python/examples/dspy-rag-fastapi/backend/main.py
- python/examples/dspy-rag-fastapi/backend/poetry.lock
- python/examples/dspy-rag-fastapi/backend/pyproject.toml
- python/examples/dspy-rag-fastapi/compose.yml
- python/examples/dspy-rag-fastapi/evaluation/evaluate.ipynb
- python/examples/dspy-rag-fastapi/frontend/about.py
- python/examples/dspy-rag-fastapi/frontend/pages/1_zero_shot_query.py
- python/examples/dspy-rag-fastapi/frontend/pages/2_compiled_query.py
- python/examples/dspy-rag-fastapi/frontend/pages/3_optimize_pipeline.py
- docs: switch from chroma to weaviate
- switch to also support Cohere
- add a notebook to run evals
> docs: switch dspy example to weaviate and cohere

- python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py
- spec/semantic_conventions.md
Reverts Arize-ai/openinference#408
> chore: Revert "feat: Add `user.id` and `session.id` to semantic conventions"

- python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py
- spec/semantic_conventions.md
Reverts Arize-ai/openinference#409
> feat: Add `user.id` and `session.id` to semantic conventions

- js/.changeset/tame-kids-yell.md
- js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
resolves https://github.com/Arize-ai/phoenix/issues/3042
> feat(js): session.id and user.id semantic conventions

- js/.changeset/funny-rocks-notice.md
- js/packages/openinference-instrumentation-openai/src/instrumentation.ts
> feat(openai-node): add the ability to manually instrument

- spec/semantic_conventions.md
Add footnote to explain how to set attributes based on lists of objects.
> fix: add footnote for how to flatten attributes based on lists of objects

- python/instrumentation/openinference-instrumentation-openai/pyproject.toml
- python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request_attributes_extractor.py
- python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_response_accumulator.py
- python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_utils.py
> fix: improve openai support for non-ascii characters

- python/instrumentation/openinference-instrumentation-mistralai/pyproject.toml
- python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_chat_wrapper.py
- python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_request_attributes_extractor.py
- python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_response_accumulator.py
- python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_utils.py
> fix: improve mistral support for non-ascii characters

- python/instrumentation/openinference-instrumentation-dspy/pyproject.toml
- python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py
> fix: improve dspy support for non-ascii characters

- python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
- python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_callback.py
> fix: improve llama-index support for non-ascii characters

- python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
- python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
> fix: improve langchain support for non-ascii characters

- python/instrumentation/openinference-instrumentation-bedrock/pyproject.toml
- python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/__init__.py
> fix: improve bedrock support for non-ascii characters

- python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
> fix: further llama-index support for non-ascii characters

- python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py
> fix: further dspy support for non-ascii characters

- js/.changeset/heavy-dryers-happen.md
- js/packages/openinference-semantic-conventions/src/index.ts
- js/packages/openinference-semantic-conventions/src/resource/SemanticResourceAttributes.ts
- js/packages/openinference-semantic-conventions/src/resource/index.ts
Adds resource attributes for project name.
> feat(js): add semcov resource atters for project name

- python/instrumentation/openinference-instrumentation-openai/README.md
- python/instrumentation/openinference-instrumentation-openai/examples/chat_completions.py
- python/instrumentation/openinference-instrumentation-openai/examples/chat_completions_async_stream.py
- python/instrumentation/openinference-instrumentation-openai/examples/chat_completions_async_stream_with_raw_response.py
- python/instrumentation/openinference-instrumentation-openai/examples/chat_completions_stream.py
- python/instrumentation/openinference-instrumentation-openai/examples/chat_completions_stream_with_raw_response.py
- python/instrumentation/openinference-instrumentation-openai/examples/chat_completions_with_function_calling.py
- python/instrumentation/openinference-instrumentation-openai/examples/chat_completions_with_raw_response.py
- python/instrumentation/openinference-instrumentation-openai/examples/chat_completions_with_streaming_response.py
- python/instrumentation/openinference-instrumentation-openai/examples/embeddings.py
- python/instrumentation/openinference-instrumentation-openai/examples/requirements.txt
- python/instrumentation/openinference-instrumentation-openai/examples/with_httpx_instrumentor.py
> refactor: add token counts to openai streaming examples

- python/instrumentation/openinference-instrumentation-mistralai/pyproject.toml
```
py39-ci-mistralai-latest: FAIL ✖ in 29.07 seconds
py39-ci-mistralai: OK ✔ in 32.75 seconds
py312-ci-mistralai-latest: FAIL ✖ in 33.48 seconds
py312-ci-mistralai: OK ✔ in 35.23 seconds
```
> refactor: fix tests for mistralai v0.1

- python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_chat_wrapper.py
- python/instrumentation/openinference-instrumentation-mistralai/tests/openinference/instrumentation/mistralai/test_instrumentor.py
> fix: remove unnecessary `MistralClient` instantiation

- python/instrumentation/openinference-instrumentation-langchain/examples/custom_retriever.py
- python/instrumentation/openinference-instrumentation-langchain/examples/pathway_retriever.py
Add minimum working examples of custom retrievers.
> docs: minimum working example of a custom retriever

- python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/__init__.py
- python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
- python/instrumentation/openinference-instrumentation-langchain/tests/openinference/instrumentation/langchain/test_instrumentor.py
Retriever gets a separate trace because the Tracer was re-instantiated and the span can't find its parent.
Retriever span can now find its parent because the Tracer was not re-instantiated.
> fix: make tracer a singleton instance

- python/instrumentation/openinference-instrumentation-langchain/examples/chain_metadata.py
- python/instrumentation/openinference-instrumentation-langchain/examples/custom_retriever.py
- python/instrumentation/openinference-instrumentation-langchain/examples/exchange_rate_tool.py
- python/instrumentation/openinference-instrumentation-langchain/examples/openai_chat_stream.py
- python/instrumentation/openinference-instrumentation-langchain/examples/pathway_retriever.py
- python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
> fix: handle ToolMessage in LangChain instrumentor

- js/.changeset/hip-trees-whisper.md
- js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
- python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py
- spec/traces.md
Add guardrails span kind to list of span kinds
> feat: Add guardrails span kind

- python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py
- spec/traces.md
resolves https://github.com/Arize-ai/phoenix/issues/3634
> feat: add evaluator span kind to semantic conventions

- js/packages/openinference-instrumentation-openai/test/openai.test.ts
- js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
fixes Arize-ai/arize [#33290](https://github.com/Arize-ai/arize/issues/33290)
> fix(js): fix lowercase values in semantic conventions

- js/package.json
- js/packages/openinference-instrumentation-langchain/package.json
- js/packages/openinference-instrumentation-llama-index/package.json
- js/packages/openinference-instrumentation-openai/package.json
- js/pnpm-lock.yaml
> chore: update js deps

- python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
- python/instrumentation/openinference-instrumentation-langchain/tests/test_instrumentor.py
- python/tox.ini
resolves [#3814](https://github.com/Arize-ai/phoenix/issues/3814)
> fix: include token counts from langchain ChatAnthropic model

- python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_callback.py
> fix: allow `raw` to be dict or object for llama-index v0.10.58

- spec/configuration.md
> fix: Fix configuraiton table

- python/instrumentation/openinference-instrumentation-langchain/examples/image_openai.py
- python/instrumentation/openinference-instrumentation-langchain/examples/image_vertexai.py
- python/instrumentation/openinference-instrumentation-langchain/examples/requirements.txt
- python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
- python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
- python/instrumentation/openinference-instrumentation-langchain/tests/test_image_in_message.py
> feat(langchain): capture image in chat message

- python/pull_request_template.md
Adds a pull request template for python
> docs: Update pull_request_template.md

- python/instrumentation/openinference-instrumentation-llama-index/examples/multimodal_stream_chat_with_config.py
- python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
- python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/__init__.py
- python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
- python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_handler_config.py
> feat: Add config handling to instrumentation

- js/packages/openinference-core/src/trace/promptTemplate.ts
- js/packages/openinference-core/test/promptTemplate.test.ts
- js/packages/openinference-core/test/session.test.ts
- js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
> feat(openinference-core): js support for prompt templates

- README.md
- release-please-config.json
Modified README.md and release-please-config.json for liteLLM release
> feat(litellm): add README and release please for liteLLM

- python/instrumentation/openinference-instrumentation-vertexai/pyproject.toml
- python/instrumentation/openinference-instrumentation-vertexai/src/openinference/instrumentation/vertexai/__init__.py
- python/instrumentation/openinference-instrumentation-vertexai/tests/test_gapic_client.py
> feat(vertexai): Enable configuration using common instrumentation pkg

- python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
- python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/__init__.py
- python/instrumentation/openinference-instrumentation-langchain/tests/test_config.py
> feat(langchain): Enable configuration using common instrumentation pkg

- python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
- python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
- python/instrumentation/openinference-instrumentation-langchain/tests/cassettes/test_instrumentor/test_records_token_counts_for_streaming_openai_llm.yaml
- python/instrumentation/openinference-instrumentation-langchain/tests/test_instrumentor.py
> fix: add token counts for langchain streaming

- js/packages/openinference-instrumentation-llama-index/src/instrumentation.ts
- js/packages/openinference-instrumentation-llama-index/src/types.ts
- js/packages/openinference-instrumentation-llama-index/src/utils.ts
- js/packages/openinference-instrumentation-llama-index/test/llamaIndex.test.ts
> feat(js): llama-index-ts initial retrieval span support

- python/instrumentation/openinference-instrumentation-bedrock/pyproject.toml
- python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/__init__.py
- python/instrumentation/openinference-instrumentation-bedrock/tests/test_instrumentor.py
- python/instrumentation/openinference-instrumentation-dspy/pyproject.toml
- python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py
- python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
- python/instrumentation/openinference-instrumentation-guardrails/pyproject.toml
- python/instrumentation/openinference-instrumentation-guardrails/src/openinference/instrumentation/guardrails/__init__.py
- python/instrumentation/openinference-instrumentation-guardrails/tests/openinference/instrumentation/guardrails/test_instrumentor.py
- python/instrumentation/openinference-instrumentation-mistralai/pyproject.toml
- python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/__init__.py
- python/instrumentation/openinference-instrumentation-mistralai/tests/openinference/instrumentation/mistralai/test_instrumentor.py
Closes https://github.com/Arize-ai/openinference/issues/730
Closes https://github.com/Arize-ai/openinference/issues/732
Closes https://github.com/Arize-ai/openinference/issues/733
Closes https://github.com/Arize-ai/openinference/issues/736
> feat: Enable config propagation

- python/instrumentation/openinference-instrumentation-promptflow/examples/chat_flow_example_to_arize.ipynb
- python/instrumentation/openinference-instrumentation-promptflow/examples/chat_flow_example_to_phoenix.ipynb
- python/instrumentation/openinference-instrumentation-promptflow/examples/flow.py
- Ruff formatted flow.py
- Added notebook demo walkthrough with Arize as collector
- Renamed the Phoenix walkthrough
> feat(promptflow): Added prompt flow example that exports traces to Arize

- python/instrumentation/openinference-instrumentation-llama-index/examples/requirements.txt
- python/instrumentation/openinference-instrumentation-llama-index/examples/workflow.py
- python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
> fix: ignore `WorkflowDone` exception

- js/.changeset/early-lobsters-cough.md
- js/packages/openinference-core/README.md
- js/packages/openinference-core/jest.config.js
- js/packages/openinference-core/package.json
- js/packages/openinference-core/src/index.ts
- js/packages/openinference-core/src/trace/contextAttributes.ts
- js/packages/openinference-core/src/trace/index.ts
- js/packages/openinference-core/src/trace/types.ts
- js/packages/openinference-core/src/utils/index.ts
- js/packages/openinference-core/src/utils/typeUtils.ts
- js/packages/openinference-core/src/utils/types.ts
- js/packages/openinference-core/test/trace/contextAttributes.test.ts
- js/packages/openinference-core/test/utils/typeUtils.test.ts
- js/packages/openinference-core/tsconfig.esm.json
- js/packages/openinference-core/tsconfig.esnext.json
- js/packages/openinference-core/tsconfig.json
- js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
- js/pnpm-lock.yaml
resolves #356 
adds context propagation of certain semantic attributes such as session, user, metadata etc.
> feat(js): openinference-core

- python/instrumentation/openinference-instrumentation-haystack/examples/building_fallbacks_with_conditional_routing.py
adds haystack example for https://haystack.deepset.ai/tutorials/36_building_fallbacks_with_conditional_routing
> chore: add haystack example

- python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/_wrappers.py
- python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/test_instrumentor.py
> fix: Setting of attributes crashes Phoenix and default some components to chain

- js/packages/openinference-instrumentation-llama-index/package.json
- js/packages/openinference-instrumentation-llama-index/src/instrumentation.ts
- js/packages/openinference-instrumentation-llama-index/src/types.ts
- js/packages/openinference-instrumentation-llama-index/src/utils.ts
- js/packages/openinference-instrumentation-llama-index/test/llamaIndex.test.ts
- js/packages/openinference-instrumentation-llama-index/tsconfig.json
- js/pnpm-lock.yaml
> feat(js): llama-index-ts embeddings support

- js/.changeset/mighty-adults-bake.md
- js/packages/openinference-instrumentation-openai/src/instrumentation.ts
- js/packages/openinference-instrumentation-openai/test/openai.test.ts
> feat(openai): capture images in request

- js/examples/openai/README.md
- js/examples/openai/backend/index.ts
- js/examples/openai/backend/package-lock.json
- js/examples/openai/backend/package.json
- js/examples/openai/backend/src/controllers/chat.controller.ts
- js/examples/openai/backend/src/controllers/feedback.controller.ts
- js/examples/openai/backend/src/routes/feedback.route.ts
- js/examples/openai/compose.yml
- js/examples/openai/frontend/Dockerfile
- js/examples/openai/frontend/app/components/chat-section.tsx
- js/examples/openai/frontend/app/components/transform.ts
- js/examples/openai/frontend/app/components/ui/chat/chat-item.tsx
- js/examples/openai/frontend/app/components/ui/chat/chat-messages.tsx
- js/examples/openai/frontend/app/components/ui/icons.tsx
- js/examples/openai/frontend/package-lock.json
- js/examples/openai/frontend/package.json
partially resolves: https://github.com/Arize-ai/phoenix/issues/4140
- adds feedback to open ai instrumentation example
May want to move this into phoenix repo
https://github.com/user-attachments/assets/bbdfeb47-eab7-4491-a3b0-2851f39346f7
> docs(annotations): add annotations to openai example

- .github/workflows/python-CI.yaml
> ci: Update python-CI.yaml to run on: oss-4-core-runner

- .github/workflows/python-cron.yaml
> ci(python): add slack notification for failed cron job

- python/dev-requirements.txt
This reverts commit 45794db4afc0b8c7813f80e729c2c43063ce736b.
> ci: revert uv dev req

- python/tox.ini
Ensure `uv` does not use the cache when installing local libraries.
> ci: ensure `uv` installs local libraries in editable mode

- python/tox.ini
somehow mypy check failed with editable install
> ci(python): replace editable install with reinstall

- .github/workflows/python-CI.yaml
- python/instrumentation/openinference-instrumentation-langchain/tests/test_instrumentor.py
> ci: fix metadata for langchain-latest

- python/instrumentation/openinference-instrumentation-crewai/pyproject.toml
- python/instrumentation/openinference-instrumentation-crewai/src/openinference/instrumentation/crewai/__init__.py
- python/instrumentation/openinference-instrumentation-crewai/src/openinference/instrumentation/crewai/_wrappers.py
- python/instrumentation/openinference-instrumentation-crewai/tests/openinference/instrumentation/crewai/test_instrumentor.py
Resolves: #731 
Resolves: #748 
Resolves: #719 
Notes:
- Trace config is implemented and tested
- Suppress tracing is implemented
- Context attributes is implemented and testing framework is in place but cannot be tested until crewAI tests are implemented
> feat(crewAI): Added trace config, context attributes, suppress tracing for CrewAI

- .github/workflows/python-cron.yaml
slack block [builder](https://app.slack.com/block-kit-builder/TT4DHP98W#%7B%22blocks%22:%5B%7B%22type%22:%22rich_text%22,%22elements%22:%5B%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22link%22,%22url%22:%22http://github.com%22,%22text%22:%22CI%20Failures%20for%20Python%20Packages%22,%22style%22:%7B%22bold%22:true%7D%7D%5D%7D,%7B%22type%22:%22rich_text_list%22,%22style%22:%22ordered%22,%22elements%22:%5B%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22py312-ci-mistralai-latest%22%7D%5D%7D,%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22py312-ci-guardrails-latest%22%7D%5D%7D%5D%7D%5D%7D%5D%7D)
> ci(python): rich text for slack

- .github/workflows/python-cron.yaml
Reverts Arize-ai/openinference#868
> revert: "ci(python): rich text for slack"

- python/instrumentation/openinference-instrumentation-haystack/examples/cohere_reranker.py
- python/instrumentation/openinference-instrumentation-haystack/examples/requirements.txt
- python/instrumentation/openinference-instrumentation-haystack/pyproject.toml
- python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/_wrappers.py
- python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/cassettes/test_instrumentor/test_cohere_reranker_span_has_expected_attributes.yaml
- python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/cassettes/test_instrumentor/test_error_status_code_and_exception_events_with_invalid_api_key.yaml
- python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/test_instrumentor.py
- python/tox.ini
- Improves logic distinguishing retrievers and rerankers
- Implements reranker spans
> feat: add re-ranker support in haystack

- python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/_wrappers.py
- python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/cassettes/test_instrumentor/test_pipeline_with_chat_prompt_builder_and_chat_generator_produces_expected_spans.yaml
- python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/test_instrumentor.py
- python/tox.ini
- Masks embeddings from output value.
- Improves span naming.
- Fixes tests to run on latest version of `haystack-ai`.
resolves #901
resolves #898
> fix(haystack): improve span names and mask output embeddings

- python/tox.ini
https://github.com/Arize-ai/openinference/issues/832
> ci: limit mistralai < 1

- python/dev-requirements.txt
- python/instrumentation/openinference-instrumentation-openai/pyproject.toml
- python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request_attributes_extractor.py
- python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/conftest.py
- python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/test_instrumentor.py
- python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/test_tool_calls.py
- python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py
Resolves #834
Resolves #688 
This PR adds a new semantic convention for capturing tool definitions for vendor OpenAI.
> feat: Added tools attribute

- python/openinference-instrumentation/src/openinference/instrumentation/config.py
- python/openinference-instrumentation/tests/conftest.py
- python/openinference-instrumentation/tests/test_config.py
> feat: attribute prioritization

- js/.changeset/fresh-seals-judge.md
- js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
> feat(js): Added tools and tool_json_schema definitions to js semantic conventions

- python/instrumentation/openinference-instrumentation-anthropic/examples/end_to_end_tool_use.py
- python/instrumentation/openinference-instrumentation-anthropic/examples/requirements.txt
- python/instrumentation/openinference-instrumentation-anthropic/pyproject.toml
Anthropic doesn't really give good examples of how to continue a conversation after making a tool call. Constructed this example by following the instructions [here](https://docs.anthropic.com/en/docs/build-with-claude/tool-use#handling-tool-use-and-tool-result-content-blocks).
> chore(anthropic): add example and requirements file for anthropic examples

- python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/_wrappers.py
> fix(haystack): ensure haystack is not a runtime dependency

- js/examples/langchain-express/backend/package-lock.json
- js/examples/langchain-express/backend/package.json
- js/examples/langchain-express/backend/src/controllers/chat.controller.ts
> docs(examples): update langchain express example to langchain v0.2.x

- python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/__init__.py
> fix(bedrock): ensure bedrock instrumentation does not break runtime for BedrockEmbeddings model from langchain

- python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/__init__.py
- python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/_wrappers.py
> chore(anthropic): dynamically import anthropic

- python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/_wrappers.py
resolves #953
trigger pipeline for https://github.com/Arize-ai/openinference/pull/996
> fix(anthropic): dynamically import anthropic

- python/openinference-instrumentation/src/openinference/instrumentation/logging.py
> fix: remove setting the global logger level

- python/instrumentation/openinference-instrumentation-llama-index/examples/neutrino_query_engine.py
- python/instrumentation/openinference-instrumentation-llama-index/examples/openai_stream_chat.py
- python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
Ensures LlamaIndex response models are serializable.
resolves https://github.com/Arize-ai/phoenix/issues/4423
> fix(llama-index): ensure llamaindex response models are serializable

- python/openinference-instrumentation/src/openinference/instrumentation/config.py
- python/openinference-instrumentation/tests/test_id_generator.py
> feat: id generator with separate source of randomness

- js/packages/openinference-instrumentation-openai/examples/chat.ts
- js/packages/openinference-instrumentation-openai/examples/instrumentation.ts
- js/packages/openinference-instrumentation-openai/examples/manual-instrumentation.ts
- js/packages/openinference-instrumentation-openai/package.json
- js/pnpm-lock.yaml
Show an example of how to manually instrument openai
> chore(openai-node): add manual instrumentation example

- python/tox.ini
> ci: remove instructor latest in tox

- python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
- python/instrumentation/openinference-instrumentation-langchain/tests/_helpers.py
- python/instrumentation/openinference-instrumentation-langchain/tests/conftest.py
- python/instrumentation/openinference-instrumentation-langchain/tests/test_instrumentor.py
- python/tox.ini
> feat: support langchain 0.3

- python/instrumentation/openinference-instrumentation-groq/src/openinference/instrumentation/groq/_request_attributes_extractor.py
- python/instrumentation/openinference-instrumentation-groq/src/openinference/instrumentation/groq/_utils.py
- python/instrumentation/openinference-instrumentation-groq/src/openinference/instrumentation/groq/_with_span.py
- python/instrumentation/openinference-instrumentation-groq/src/openinference/instrumentation/groq/_wrappers.py
- python/instrumentation/openinference-instrumentation-groq/tests/test_instrumentor.py
previous implementation was not setting the correct attributes for input / output. I've also refactored this instrumentation so it uses the request extractor pattern that is found in other packages
> fix: groq input messages

- js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
> fix: gcp -> google

- python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/_wrappers.py
- python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/test_instrumentor.py
resolves https://github.com/Arize-ai/phoenix/issues/5192
> feat(anthropic): add llm provider and system attributes to anthropic instrumentation

- python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request.py
- python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request_attributes_extractor.py
- python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/test_instrumentor.py
Adds llm provider and system attributes to openai instrumentation
resolves [#5191](https://github.com/Arize-ai/phoenix/issues/5191)
> feat(openai): add llm provider and system attributes

- python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/_wrappers.py
creates helper functions for attributes
> refactor(anthropic): create helper functions for wrangling attributes

- python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/_wrappers.py
- python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/test_instrumentor.py
adds tool json schema attributes to anthropic instrumentation
resolves #1068
> feat(anthropic): add tool json schema attributes to anthropic instrumentation

- python/instrumentation/openinference-instrumentation-openai/pyproject.toml
- python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request.py
- python/instrumentation/openinference-instrumentation-openai/test-requirements.txt
- python/tox.ini
> fix: remove httpx dependency

- python/instrumentation/openinference-instrumentation-anthropic/pyproject.toml
- python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/__init__.py
- python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/_stream.py
- python/instrumentation/openinference-instrumentation-anthropic/test-requirements.txt
- python/tox.ini
> fix: remove anthropic dependency

- js/examples/langchain-express/.env.example
- js/examples/langchain-express/README.md
- js/examples/langchain-express/backend/.dockerignore
- js/examples/langchain-express/backend/Dockerfile
- js/examples/langchain-express/compose.yml
- js/examples/langchain-express/frontend/.dockerignore
- js/examples/langchain-express/frontend/Dockerfile
- js/examples/llama-index-express/.env.example
- js/examples/llama-index-express/README.md
- js/examples/llama-index-express/backend/.dockerignore
- js/examples/llama-index-express/backend/Dockerfile
- js/examples/llama-index-express/compose.yml
- js/examples/llama-index-express/frontend/.dockerignore
- js/examples/llama-index-express/frontend/Dockerfile
Minor tweaks to the Dockerfiles to prevent errors with lockfiles and node_module conflicts.
README tweaks
Slightly slimmer final images and slightly faster docker compose builds
> chore(js): Fix langchain-express and llama-index-express docker examples

- python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/_wrappers.py
resolves https://github.com/Arize-ai/openinference/issues/1109
> fix: add tool id for anthropic instrumentor and serialize `content` to string if it's not a string

- python/tox.ini
related https://github.com/Arize-ai/phoenix/issues/5575
> ci: restrict httpx version <0.28

- python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
- python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
- python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/cassettes/test_groq_astream_chat_token_count.yaml
- python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_token_counts.py
- python/tox.ini
resolves https://github.com/Arize-ai/phoenix/issues/5729
> fix(llama-index): extract token counts for groq when streaming

- python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
> fix(llama-index): coerce token counts to be integers

- release-please-config.json
resolves https://github.com/Arize-ai/openinference/issues/1197
> ci: set up release please for smolagents

- python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
- python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/__init__.py
- python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
- python/instrumentation/openinference-instrumentation-langchain/tests/cassettes/test_instrumentor/test_gemini_token_counts.yaml
- python/instrumentation/openinference-instrumentation-langchain/tests/cassettes/test_instrumentor/test_gemini_token_counts_streaming.yaml
- python/instrumentation/openinference-instrumentation-langchain/tests/test_instrumentor.py
> fix: Fix missing token counts when using VertexAI with Langchain Instrumentor

- python/instrumentation/openinference-instrumentation-dspy/examples/requirements.txt
- python/instrumentation/openinference-instrumentation-dspy/pyproject.toml
- python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py
- python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/package.py
- python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
- python/mypy.ini
Fixes https://github.com/Arize-ai/openinference/issues/1248 by upgrading dspy
> fix(dspy): dspy 2.6.0 upgrade

- python/tox.ini
> ci: remove httpx restriction

- python/instrumentation/openinference-instrumentation-smolagents/src/openinference/instrumentation/smolagents/_wrappers.py
- python/instrumentation/openinference-instrumentation-smolagents/tests/openinference/instrumentation/smolagents/cassettes/test_instrumentor/TestModels.test_openai_server_model_has_expected_attributes.yaml
- python/instrumentation/openinference-instrumentation-smolagents/tests/openinference/instrumentation/smolagents/cassettes/test_instrumentor/TestModels.test_openai_server_model_with_tool_has_expected_attributes.yaml
- python/instrumentation/openinference-instrumentation-smolagents/tests/openinference/instrumentation/smolagents/test_instrumentor.py
Adds suport for smolagents' new nested "text" llm input message contents.
Fixes #1237
> fix(smolagents): support smolagents nested llm input message contents

- .github/workflows/python-CI.yaml
- python/instrumentation/openinference-instrumentation-anthropic/pyproject.toml
- python/instrumentation/openinference-instrumentation-anthropic/test-requirements.txt
- python/instrumentation/openinference-instrumentation-autogen/pyproject.toml
- python/instrumentation/openinference-instrumentation-crewai/pyproject.toml
- python/instrumentation/openinference-instrumentation-dspy/pyproject.toml
- python/instrumentation/openinference-instrumentation-groq/pyproject.toml
- python/instrumentation/openinference-instrumentation-guardrails/pyproject.toml
- python/instrumentation/openinference-instrumentation-haystack/pyproject.toml
- python/instrumentation/openinference-instrumentation-instructor/pyproject.toml
- python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
- python/instrumentation/openinference-instrumentation-litellm/pyproject.toml
- python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
- python/instrumentation/openinference-instrumentation-mistralai/pyproject.toml
- python/instrumentation/openinference-instrumentation-openai/pyproject.toml
- python/instrumentation/openinference-instrumentation-openai/test-requirements.txt
- python/instrumentation/openinference-instrumentation-vertexai/pyproject.toml
- python/openinference-instrumentation/pyproject.toml
- python/openinference-semantic-conventions/pyproject.toml
- python/tox.ini
resolves https://github.com/Arize-ai/openinference/issues/1070
> fix: support python 3.13 and drop python 3.8

- python/instrumentation/openinference-instrumentation-smolagents/src/openinference/instrumentation/smolagents/_wrappers.py
Support new simplified managed agents.
Fix #1253.
CC: @nate-mar
> fix(smolagents): support new managed agents

- python/instrumentation/openinference-instrumentation-smolagents/pyproject.toml
> feat(smolagents): support smolagents on python 3.13

- python/instrumentation/openinference-instrumentation-anthropic/pyproject.toml
- python/instrumentation/openinference-instrumentation-autogen/pyproject.toml
- python/instrumentation/openinference-instrumentation-bedrock/pyproject.toml
- python/instrumentation/openinference-instrumentation-crewai/pyproject.toml
- python/instrumentation/openinference-instrumentation-dspy/pyproject.toml
- python/instrumentation/openinference-instrumentation-groq/pyproject.toml
- python/instrumentation/openinference-instrumentation-guardrails/pyproject.toml
- python/instrumentation/openinference-instrumentation-haystack/pyproject.toml
- python/instrumentation/openinference-instrumentation-instructor/pyproject.toml
- python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
- python/instrumentation/openinference-instrumentation-litellm/pyproject.toml
- python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
- python/instrumentation/openinference-instrumentation-mistralai/pyproject.toml
- python/instrumentation/openinference-instrumentation-openai/pyproject.toml
- python/instrumentation/openinference-instrumentation-smolagents/pyproject.toml
- python/instrumentation/openinference-instrumentation-vertexai/pyproject.toml
resolves https://github.com/Arize-ai/phoenix/issues/6406
> feat: define openinference_instrumentor entry points for all libraries

- python/instrumentation/openinference-instrumentation-llama-index/examples/multi_tool_calling.py
- python/instrumentation/openinference-instrumentation-llama-index/examples/requirements.txt
- python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
> fix(llama-index): Capture tool call id from additional_kwargs

- js/package.json
- js/pnpm-lock.yaml
> fix(js): update dependancies for security

- python/openinference-instrumentation/src/openinference/instrumentation/config.py
- python/openinference-instrumentation/tests/test_id_generator.py
> fix: allow user override of id generator

- python/instrumentation/openinference-instrumentation-litellm/src/openinference/instrumentation/litellm/__init__.py
- python/instrumentation/openinference-instrumentation-litellm/tests/test_instrumentor.py
resolves: https://github.com/Arize-ai/openinference/issues/1273
resolves: https://github.com/Arize-ai/openinference/issues/1227
> fix(liteLLM): support sync stream

- python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/_processor.py
> fix: attach span to context

- python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/_processor.py
> fix: reclassify handoff span as tool span

- python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
> fix: replace logger.exception() with repr()

- python/instrumentation/openinference-instrumentation-smolagents/pyproject.toml
- python/instrumentation/openinference-instrumentation-smolagents/src/openinference/instrumentation/smolagents/__init__.py
Fixes https://github.com/Arize-ai/openinference/issues/1399
> fix: only import exported smolagents models

- js/packages/openinference-instrumentation-beeai/examples/README.md
Small improvements in the `examples/readme.md` file.
> feat(beeai): update examples docs

- python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/_processor.py
Fixes https://github.com/Arize-ai/openinference/issues/1418
> fix: openai agent with int tool return

- python/openinference-instrumentation/src/openinference/instrumentation/__init__.py
- python/openinference-instrumentation/src/openinference/instrumentation/_attributes.py
- python/openinference-instrumentation/src/openinference/instrumentation/_spans.py
- python/openinference-instrumentation/src/openinference/instrumentation/_tracer_providers.py
- python/openinference-instrumentation/src/openinference/instrumentation/_tracers.py
- python/openinference-instrumentation/src/openinference/instrumentation/_types.py
- python/openinference-instrumentation/src/openinference/instrumentation/config.py
- python/openinference-instrumentation/tests/test_config.py
- python/openinference-instrumentation/tests/test_manual_instrumentation.py
> refactor: move tracer-related code into sub-modules

- python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/_processor.py
> fix: get attributes from GenerationSpanData (i.e. chat completions api)

- python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
- python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/_processor.py
- python/instrumentation/openinference-instrumentation-openai-agents/test-requirements.txt
Fix CI failures caught by the daily cron job -  https://github.com/Arize-ai/openinference/actions/runs/14113656017/job/39538538313
> ci: fix failing tests py39-ci-openai_agents-latest and py39-ci-dspy-latest

- python/instrumentation/openinference-instrumentation-llama-index/README.md
- python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
- python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
- python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_message_content_blocks.py
- python/tox.ini
> feat!: support chat message content blocks for llama-index >= 0.12.3

- js/.changeset/large-pants-switch.md
- js/packages/openinference-instrumentation-openai/src/instrumentation.ts
> fix(openai): Rewrite namespace import to default import

- python/instrumentation/openinference-instrumentation-openai-agents/pyproject.toml
- python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/_processor.py
- python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/package.py
- python/instrumentation/openinference-instrumentation-openai-agents/test-requirements.txt
- python/instrumentation/openinference-instrumentation-openai-agents/tests/test_span_attribute_helpers.py
- capturing the list of tool names
- update min version to openai-agents >= 0.0.7
resolves #1448
resolves #1375
> feat: capture result from MCPListToolsSpanData

- python/instrumentation/openinference-instrumentation-crewai/README.md
- python/instrumentation/openinference-instrumentation-crewai/src/openinference/instrumentation/crewai/_wrappers.py
- python/instrumentation/openinference-instrumentation-crewai/tests/openinference/instrumentation/crewai/fixtures/crew_session.yaml
- python/instrumentation/openinference-instrumentation-crewai/tests/openinference/instrumentation/crewai/fixtures/crew_session_context_attributes.yaml
- python/instrumentation/openinference-instrumentation-crewai/tests/openinference/instrumentation/crewai/test_instrumentor.py
This PR introduces a new helper function `_set_response_attributes` to standardize how response attributes are set across different wrappers in the CrewAI instrumentation. This change improves code maintainability and ensures consistent behavior when handling different response types.
- Added `_set_response_attributes` helper function that handles:
- Objects with `to_dict` method
- Dictionary responses
- Other response types
- Updated all wrappers to use the new helper function:
- `_ExecuteCoreWrapper`
- `_KickoffWrapper`
- `_ToolUseWrapper`
- **Consistency**: Ensures uniform handling of response attributes across all wrappers
- **Maintainability**: Reduces code duplication and centralizes response formatting logic
- **Reliability**: Standardizes how different response types are processed …
> refactor: (crewAI) Support handle response attribute properly 

- python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/_wrappers.py
- python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/cassettes/test_instrumentor/test_anthropic_instrumentation_messages_token_counts.yaml
- python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/test_instrumentor.py
resolves: #1462
captures anthropic's `usage.cache_read_input_tokens` and `usage.cache_creation_input_tokens` and map them to span attributes `llm.token_count.prompt_details.cache_read` and `llm.token_count.prompt_details.cache_write`
> feat: instrumentation-anthropic cache token counts

- js/packages/openinference-instrumentation-openai/src/instrumentation.ts
- js/packages/openinference-instrumentation-openai/test/openai.test.ts
> feat(openai-node-sdk): prompt and completion cache / reasoning / audio tokens

- python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
> fix: tuple message type

- python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
- python/instrumentation/openinference-instrumentation-langchain/tests/test_instrumentor.py
- python/instrumentation/openinference-instrumentation-langchain/tests/test_merged_metadata.py
> fix: merge metadata

- python/dev-requirements.txt
- python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
- python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
- python/instrumentation/openinference-instrumentation-llama-index/test-requirements.txt
- python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/conftest.py
- python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_chat_with_tools.py
- python/tox.ini
> fix: capture tools from chat kwargs

- python/instrumentation/openinference-instrumentation-beeai/README.md
- python/instrumentation/openinference-instrumentation-beeai/examples/react_agent_basic.py
- python/instrumentation/openinference-instrumentation-beeai/examples/requirements.txt
- python/instrumentation/openinference-instrumentation-beeai/examples/toolcalling_agent_basic.py
- python/instrumentation/openinference-instrumentation-beeai/pyproject.toml
- python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/__init__.py
- python/instrumentation/openinference-instrumentation-beeai/uv.lock
I need to publish a new package version with small fixes and a new beeai framework version.
I run ` git commit --allow-empty -m "fix: beeai python package" -m "Release-As: 0.1.1"`. Is there anything else I need to do on my site to create a PR for publishing a new version?
> fix: beeai python package

- js/.changeset/plenty-humans-kneel.md
- js/packages/openinference-instrumentation-beeai/examples/instrumentation.ts
- js/packages/openinference-instrumentation-beeai/package.json
- js/packages/openinference-instrumentation-beeai/src/instrumentation.ts
- js/pnpm-lock.yaml
I implemented the strict version range for the BeeAI framework (JS version).
Closes: https://github.com/i-am-bee/beeai-framework/issues/770
> feat(beeai): fix latest js framework version

- python/instrumentation/openinference-instrumentation-beeai/examples/requirements.txt
- python/instrumentation/openinference-instrumentation-beeai/pyproject.toml
- python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/__init__.py
- python/instrumentation/openinference-instrumentation-beeai/uv.lock
> feat: update beeai framework package

- js/.changeset/slimy-pumas-rescue.md
- js/packages/openinference-instrumentation-openai/README.md
- js/packages/openinference-instrumentation-openai/examples/manual-instrumentation.ts
- js/packages/openinference-instrumentation-openai/examples/responses.ts
- js/packages/openinference-instrumentation-openai/package.json
- js/packages/openinference-instrumentation-openai/src/instrumentation.ts
- js/packages/openinference-instrumentation-openai/src/responsesAttributes.ts
- js/packages/openinference-instrumentation-openai/test/openai.responses.test.ts
- js/pnpm-lock.yaml
- python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_attributes/_responses_api.py
Instruments OpenAI Responses api
```js
const span = {
'openinference.span.kind': 'LLM',
'llm.model_name': 'gpt-4.1-2025-04-14',
'input.value': '{"model":"gpt-4.1","tools":[{"type":"web_search_preview"}],"input":"What was a positive news story from today?"}',
'input.mime_type': 'application/json',
'llm.invocation_parameters': '{"model":"gpt-4.1","tools":[{"type":"web_search_preview"}]}',
'llm.system': 'openai',
'llm.provider': 'openai',
'llm.input_messages.0.message.role': 'user',
'llm.input_messages.0.message.content': 'What was a positive news story from today?',
'llm.tools.0.tool.json_schema': '{"type":"web_search_preview"}',
'output.value': `{"id":"resp_68029412ab108191baa30e7e229b9b280ca9621eb0ea81f7","object":"response","created_at":1744999442,"status":"completed","error":null,"incomp …
```
> feat(openai-js): Instrument openai responses api

- python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_response_attributes_extractor.py
- python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/cassettes/TestTokenCounts.test_openai.yaml
- python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/test_instrumentor.py
- python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/test_token_counts.py
resolves: https://github.com/Arize-ai/openinference/issues/1455
Audio and reasoning token counts support for OpenAI
> feat: Openai audio + reasoning token counts

- python/instrumentation/openinference-instrumentation-langchain/examples/message_deletion.py
- python/instrumentation/openinference-instrumentation-langchain/examples/requirements.txt
resolves #1435 
I cannot reproduce the bug so I would like to close it with this as evidence.
> chore(langchain): add examples as to how to delete messages

- python/instrumentation/openinference-instrumentation-vertexai/src/openinference/instrumentation/vertexai/_accumulator.py
- python/instrumentation/openinference-instrumentation-vertexai/src/openinference/instrumentation/vertexai/_wrapper.py
- python/instrumentation/openinference-instrumentation-vertexai/tests/test_gapic_client.py
> fix: support function call parts when streaming

- js/.changeset/many-needles-create.md
- js/packages/openinference-vercel/README.md
- js/packages/openinference-vercel/package.json
- js/packages/openinference-vercel/src/OpenInferenceSpanProcessor.ts
- js/packages/openinference-vercel/test/OpenInferenceSpanProcessor.test.ts
- js/pnpm-lock.yaml
> fix: Cleanup openinference-vercel readme, pinned versions, old typescript types

- python/instrumentation/openinference-instrumentation-haystack/pyproject.toml
- python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/__init__.py
- python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/_wrappers.py
- python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/test_instrumentor.py
closes https://github.com/Arize-ai/openinference/issues/1602
> fix(haystack): fixing ci issues for haystack-ai

- .github/workflows/typescript-publish.yaml
changesets currently doesn't  support `cwd`
> ci: pin changesets

- CONTRIBUTING
- python/DEVELOPMENT.md
- python/openinference-instrumentation/src/openinference/instrumentation/.gitignore
- Detailed development environment setup instructions
- Disambiguated development guides
- Missing gitignore lines for symlink modules
> docs: update readmes for development setup and fixes

- python/instrumentation/openinference-instrumentation-crewai/pyproject.toml
- python/instrumentation/openinference-instrumentation-crewai/src/openinference/instrumentation/crewai/_wrappers.py
- python/instrumentation/openinference-instrumentation-crewai/tests/openinference/instrumentation/crewai/fixtures/crew_session.yaml
- python/instrumentation/openinference-instrumentation-crewai/tests/openinference/instrumentation/crewai/fixtures/crew_session_context_attributes.yaml
- Adjusted task instrumentation to support explicit empty context lists introduced in CrewAI [0.120.0](https://github.com/crewAIInc/crewAI/releases/tag/0.120.0), [Crewai MR](https://github.com/crewAIInc/crewAI/pull/2793).
- Incorporated CrewAI fix treating all falsy context values as “no context.”
- Re-recorded tests due to changes in response behavior.
- Upgraded CrewAI from 0.95 to 0.121.
Closes https://github.com/Arize-ai/openinference/issues/1679
> fix(crewai): crewai default empty tasks

- python/instrumentation/openinference-instrumentation-smolagents/examples/env.example
- python/instrumentation/openinference-instrumentation-smolagents/examples/reasoning_content.py
- python/instrumentation/openinference-instrumentation-smolagents/examples/requirements.txt
- python/instrumentation/openinference-instrumentation-smolagents/pyproject.toml
- python/instrumentation/openinference-instrumentation-smolagents/src/openinference/instrumentation/smolagents/_wrappers.py
- python/instrumentation/openinference-instrumentation-smolagents/tests/openinference/instrumentation/smolagents/cassettes/test_instrumentor/TestModels.test_litellm_reasoning_model_has_expected_attributes.yaml
- python/instrumentation/openinference-instrumentation-smolagents/tests/openinference/instrumentation/smolagents/test_instrumentor.py
> fix(smolagents): include reasoning content

- python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py
- python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
> fix(dspy): mask api keys passed as arguments

- python/instrumentation/openinference-instrumentation-langchain/examples/runnable_sequence_with_pydantic_model.py
- python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
- python/instrumentation/openinference-instrumentation-langchain/tests/test_convert_io.py
> feat: unwrap input output keys from io values

- python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
> fix: tool call for anthropic bedrock invoke model

- python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
- python/instrumentation/openinference-instrumentation-langchain/tests/test_langgraph_tool_calls.py
resolves #1816 
Before:
After:
> feat: Instrument sssistant tool calls made by LangGraph 

- python/instrumentation/openinference-instrumentation-google-adk/src/openinference/instrumentation/google_adk/_wrappers.py
> fix: serialization of response schema in invocation parameters for google-adk

- python/instrumentation/openinference-instrumentation-beeai/examples/requirements.txt
- python/instrumentation/openinference-instrumentation-beeai/pyproject.toml
- python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/_utils.py
- python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/processors/chat.py
- python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/processors/tool.py
- add fallback for values that can't be serialized
- correctly propagate tool names in the latest version
- add cost information
Ref: https://github.com/i-am-bee/beeai-framework/issues/1000
> feat: BeeAI Framework Updates

- python/instrumentation/openinference-instrumentation-litellm/examples/litellm_openai.py
- python/instrumentation/openinference-instrumentation-litellm/src/openinference/instrumentation/litellm/__init__.py
- python/instrumentation/openinference-instrumentation-litellm/tests/test_instrumentor.py
> feat(litellm): add llm provider attributes

- python/instrumentation/openinference-instrumentation-smolagents/src/openinference/instrumentation/smolagents/_wrappers.py
Use new token_usage structure.
Fix #2081.
Close https://github.com/huggingface/smolagents/issues/1682.
> fix(smolagents): use new token_usage structure

- python/instrumentation/openinference-instrumentation-openlit/README.md
Release Please wrongly attributed [my previous PR for openinference-instrumentation-openlit](https://github.com/Arize-ai/openinference/pull/2021) to a change in openinference-instrumentation-openllmetry because of a few minor changes made in the latter. 
So I'm making a minor change in openinfernece-instrumentation-openlit in a new PR so the package gets published.
> feat: Openlit span processor

- python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/__init__.py
- python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/processors/base.py
- python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/processors/tool.py
- group all spans under a single trace
- remove unnecessary events
> fix(beeaI): dedupe traces/spans

- python/instrumentation/openinference-instrumentation-crewai/examples/requirements.txt
- python/instrumentation/openinference-instrumentation-crewai/examples/research_writer_crew.py
- python/instrumentation/openinference-instrumentation-crewai/src/openinference/instrumentation/crewai/_wrappers.py
- python/instrumentation/openinference-instrumentation-crewai/tests/test_instrumentor.py
- python/tox.ini
> feat(crewai): enhance span naming to include crew, agent, and tool context

- python/instrumentation/openinference-instrumentation-beeai/examples/chat.py
- python/instrumentation/openinference-instrumentation-beeai/examples/react_agent.py
- python/instrumentation/openinference-instrumentation-beeai/examples/requirement_agent.py
- python/instrumentation/openinference-instrumentation-beeai/examples/requirements.txt
- python/instrumentation/openinference-instrumentation-beeai/examples/tool_calling_agent.py
- python/instrumentation/openinference-instrumentation-beeai/pyproject.toml
- python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/processors/chat.py
- address breaking changes in the latest BeeAI Framework version
- please release after merging
> feat: update beeai-framework

- python/instrumentation/openinference-instrumentation-pydantic-ai/src/openinference/instrumentation/pydantic_ai/semantic_conventions.py
- python/instrumentation/openinference-instrumentation-pydantic-ai/tests/openinference/instrumentation/pydantic_ai/cassettes/test_openai_agent_and_llm_spans_v1.yaml
- python/instrumentation/openinference-instrumentation-pydantic-ai/tests/openinference/instrumentation/pydantic_ai/cassettes/test_openai_agent_and_llm_spans_v2.yaml
- python/instrumentation/openinference-instrumentation-pydantic-ai/tests/openinference/instrumentation/pydantic_ai/test_instrumentor.py
resolves: https://github.com/Arize-ai/openinference/issues/2225
> fix: pydantic-ai use final user message as input value
